/*
 RequireJS Copyright (c) 2004-2010, The Dojo Foundation All Rights Reserved.
 Available via the MIT, GPL or new BSD license.
 see: http://github.com/jrburke/requirejs for details

 jQuery JavaScript Library v1.4.2
 http://jquery.com/

 Copyright 2010, John Resig
 Dual licensed under the MIT or GPL Version 2 licenses.
 http://jquery.org/license

 Includes Sizzle.js
 http://sizzlejs.com/
 Copyright 2010, The Dojo Foundation
 Released under the MIT, BSD, and GPL Licenses.

 Date: Sat Feb 13 22:33:48 2010 -0500
*/
var require;
(function(){function E(p){return U.call(p)==="[object Function]"}var A={},C,N,ga=[],R,$,ba,ca,ha,S,ma=/^(complete|loaded)$/,T=!!(typeof window!=="undefined"&&navigator&&document),ia=!T&&typeof importScripts!=="undefined",U=Object.prototype.toString,aa,c;if(typeof require!=="undefined")if(E(require))return;else S=require;aa=require=function(p,r){if(typeof p==="string"&&!E(r))return require.get(p,r);return require.def.apply(require,arguments)};require.def=function(p,r,m,x){var v=null,w,J,K,M;if(typeof p===
"string"){w=p.indexOf("!");if(w!==-1){K=p.substring(0,w);p=p.substring(w+1,p.length)}if(!require.isArray(r)){x=m;m=r;r=[]}x=x||C.ctxName;if((w=C.contexts[x])&&(w.defined[p]||w.waiting[p]))return require}else if(require.isArray(p)){x=m;m=r;r=p;p=null}else if(require.isFunction(p)){m=p;x=r;p=null;r=[]}else{v=p;p=null;if(require.isFunction(r)){x=m;m=r;r=[]}x=x||v.context}x=x||C.ctxName;w=C.contexts[x];if(!w){w={contextName:x,config:{waitSeconds:7,baseUrl:C.baseUrl||"./",paths:{}},waiting:[],specified:{require:true,
exports:true,module:true},loaded:{require:true},urlFetched:{},defined:{},modifiers:{}};w.defined.require=require;w=C.contexts[x]=w}if(v){if(v.baseUrl)if(v.baseUrl.charAt(v.baseUrl.length-1)!=="/")v.baseUrl+="/";M=w.config.paths;require.mixin(w.config,v,true);if(v.paths){for(J in v.paths)J in A||(M[J]=v.paths[J]);w.config.paths=M}if(v.priority){aa(v.priority);w.config.priorityWait=v.priority}if(v.deps||v.callback)aa(v.deps||[],v.callback);if(!r)return require}if(r){v=r;r=[];for(J=0;J<v.length;J++)r[J]=
require.splitPrefix(v[J],p)}v=w.waiting.push({name:p,deps:r,callback:m});if(p){w.waiting[p]=v-1;w.specified[p]=true}if(p&&m&&!require.isFunction(m))w.defined[p]=m;if(C.paused||w.config.priorityWait)(C.paused||(C.paused=[])).push([K,p,r,w]);else{require.checkDeps(K,p,r,w);require.checkLoaded(x)}if(p)w.loaded[p]=true;return require};require.mixin=function(p,r,m){for(var x in r)if(!(x in A)&&(!(x in p)||m))p[x]=r[x];return require};require.version="0.12.0";C=require.s={ctxName:"_",contexts:{},skipAsync:{},
isBrowser:T,isPageLoaded:!T,readyCalls:[],doc:T?document:null};require.isBrowser=C.isBrowser;if(T){C.head=document.getElementsByTagName("head")[0];if(c=document.getElementsByTagName("base")[0])C.head=c.parentNode}require.pause=function(){if(!C.paused)C.paused=[]};require.resume=function(){var p,r,m;if(!C.contexts[C.ctxName].config.priorityWait){if(C.paused){m=C.paused;delete C.paused;for(p=0;r=m[p];p++)require.checkDeps.apply(require,r)}require.checkLoaded(C.ctxName)}};require.checkDeps=function(p,
r,m,x){if(!p)for(p=0;r=m[p];p++)if(!x.specified[r.fullName]){x.specified[r.fullName]=true;r.prefix||require.load(r.name,x.contextName)}};require.isArray=function(p){return U.call(p)==="[object Array]"};require.isFunction=E;require.get=function(p,r){if(p==="exports"||p==="module")throw new Error("require of "+p+" is not allowed.");r=r||C.ctxName;var m=C.contexts[r].defined[p];if(m===undefined)throw new Error("require: module name '"+p+"' has not been loaded yet for context: "+r);return m};require.load=
function(p,r){var m=C.contexts[r],x=m.urlFetched,v=m.loaded;C.isDone=false;v[p]||(v[p]=false);v=require.nameToUrl(p,null,r);if(!x[v]){require.attach(v,r,p);x[v]=true}m.startTime=(new Date).getTime()};require.jsExtRegExp=/\.js$/;require.normalizeName=function(p,r){if(p.charAt(0)==="."){r=r.split("/");r=r.slice(0,r.length-1);p=r.concat(p.split("/"));for(N=0;r=p[N];N++)if(r==="."){p.splice(N,1);N-=1}else if(r===".."){p.splice(N-1,2);N-=2}p=p.join("/")}return p};require.splitPrefix=function(p,r){var m=
p.indexOf("!"),x=null;if(m!==-1){x=p.substring(0,m);p=p.substring(m+1,p.length)}if(r)p=require.normalizeName(p,r);return{prefix:x,name:p,fullName:x?x+"!"+p:p}};require.nameToUrl=function(p,r,m){var x,v,w;m=C.contexts[m].config;if(p.indexOf(":")!==-1||p.charAt(0)==="/"||require.jsExtRegExp.test(p))return p;else if(p.charAt(0)===".")throw new Error("require.nameToUrl does not handle relative module names (ones that start with '.' or '..')");else{x=m.paths;p=p.split("/");for(v=p.length;v>0;v--){w=p.slice(0,
v).join("/");if(x[w]){p.splice(0,v,x[w]);break}}r=p.join("/")+(r||".js");return(r.charAt(0)==="/"||r.match(/^\w+:/)?"":m.baseUrl)+r}};require.checkLoaded=function(p){var r=C.contexts[p||C.ctxName],m=r.config.waitSeconds*1E3,x=m&&r.startTime+m<(new Date).getTime(),v,w,J="",K=false,M=false,L,W;m={};if(!r.isCheckLoaded){if(r.config.priorityWait){w=true;for(v=0;W=r.config.priorityWait[v];v++)if(!r.loaded[W]){w=false;break}if(w){delete r.config.priorityWait;require.resume()}else return}r.isCheckLoaded=
true;w=r.waiting;v=r.loaded;for(L in v)if(!(L in A)){K=true;if(!v[L])if(x)J+=L+" ";else{M=true;break}}if(!K&&!w.length)r.isCheckLoaded=false;else{if(x&&J){L=new Error("require.js load timeout for modules: "+J);L.requireType="timeout";L.requireModules=J}if(M){r.isCheckLoaded=false;if(T||ia)setTimeout(function(){require.checkLoaded(p)},50)}else{r.waiting=[];r.loaded={};for(v=0;J=w[v];v++)require.exec(J,m,w,r);r.isCheckLoaded=false;if(r.waiting.length)require.checkLoaded(p);else if(!ga.length){C.ctxName=
"_";C.isDone=true;require.callReady&&require.callReady()}}}}};require.exec=function(p,r,m,x){if(p){var v=p.name,w=p.callback;w=p.deps;var J,K,M=x.defined,L,W=[],V=false;if(v){if(r[v]||v in M)return M[v];r[v]=true}if(w)for(J=0;K=w[J];J++){K=K.name;if(K==="exports"){K=M[v]={};V=true}else K=K==="module"?{id:v,uri:v?require.nameToUrl(v,null,x.contextName):undefined}:K in M?M[K]:r[K]?undefined:require.exec(m[m[K]],r,m,x);W.push(K)}if((w=p.callback)&&require.isFunction(w)){L=require.execCb(v,w,W);if(v)if(V)L=
M[v];else if(v in M)throw new Error(v+" has already been defined");else M[v]=L}return L}};require.execCb=function(p,r,m){return r.apply(null,m)};require.onScriptLoad=function(p){var r=p.currentTarget||p.srcElement,m;if(p.type==="load"||ma.test(r.readyState)){p=r.getAttribute("data-requirecontext");m=r.getAttribute("data-requiremodule");C.contexts[p].loaded[m]=true;require.checkLoaded(p);r.removeEventListener?r.removeEventListener("load",require.onScriptLoad,false):r.detachEvent("onreadystatechange",
require.onScriptLoad)}};require.attach=function(p,r,m,x,v){var w;if(T){x=x||require.onScriptLoad;w=document.createElement("script");w.type=v||"text/javascript";w.charset="utf-8";C.skipAsync[p]||w.setAttribute("async","async");w.setAttribute("data-requirecontext",r);w.setAttribute("data-requiremodule",m);w.addEventListener?w.addEventListener("load",x,false):w.attachEvent("onreadystatechange",x);w.src=p;return c?C.head.insertBefore(w,c):C.head.appendChild(w)}else if(ia){r=C.contexts[r].loaded;r[m]=
false;importScripts(p);r[m]=true}return null};C.baseUrl=S&&S.baseUrl;if(T&&(!C.baseUrl||!C.head)){R=document.getElementsByTagName("script");ba=S&&S.baseUrlMatch?S.baseUrlMatch:/(requireplugins-|require-)?jquery[\-\d\.]*(min)?\.js(\W|$)/i;for(N=R.length-1;N>-1&&($=R[N]);N--){if(!C.head)C.head=$.parentNode;if(ca=$.src)if(ha=ca.match(ba)){C.baseUrl=ca.substring(0,ha.index);break}}}S&&aa(S)})();
(function(E,A){function C(){if(!c.isReady){try{m.documentElement.doScroll("left")}catch(a){setTimeout(C,1);return}c.ready()}}function N(a,b){b.src?c.ajax({url:b.src,async:false,dataType:"script"}):c.globalEval(b.text||b.textContent||b.innerHTML||"");b.parentNode&&b.parentNode.removeChild(b)}function ga(a,b,d,f,e,i){var j=a.length;if(typeof b==="object"){for(var q in b)ga(a,q,b[q],f,e,d);return a}if(d!==A){f=!i&&f&&c.isFunction(d);for(q=0;q<j;q++)e(a[q],b,f?d.call(a[q],q,e(a[q],b)):d,i);return a}return j?
e(a[0],b):A}function R(){return(new Date).getTime()}function $(){return false}function ba(){return true}function ca(a,b,d){d[0].type=a;return c.event.handle.apply(b,d)}function ha(a){var b,d=[],f=[],e=arguments,i,j,q,k,o,u;j=c.data(this,"events");if(!(a.liveFired===this||!j||!j.live||a.button&&a.type==="click")){a.liveFired=this;var z=j.live.slice(0);for(k=0;k<z.length;k++){j=z[k];j.origType.replace(ja,"")===a.type?f.push(j.selector):z.splice(k--,1)}i=c(a.target).closest(f,a.currentTarget);o=0;for(u=
i.length;o<u;o++)for(k=0;k<z.length;k++){j=z[k];if(i[o].selector===j.selector){q=i[o].elem;f=null;if(j.preType==="mouseenter"||j.preType==="mouseleave")f=c(a.relatedTarget).closest(j.selector)[0];if(!f||f!==q)d.push({elem:q,handleObj:j})}}o=0;for(u=d.length;o<u;o++){i=d[o];a.currentTarget=i.elem;a.data=i.handleObj.data;a.handleObj=i.handleObj;if(i.handleObj.origHandler.apply(i.elem,e)===false){b=false;break}}return b}}function S(a,b){return"live."+(a&&a!=="*"?a+".":"")+b.replace(/\./g,"`").replace(/ /g,
"&")}function ma(a){return!a||!a.parentNode||a.parentNode.nodeType===11}function T(a,b){var d=0;b.each(function(){if(this.nodeName===(a[d]&&a[d].nodeName)){var f=c.data(a[d++]),e=c.data(this,f);if(f=f&&f.events){delete e.handle;e.events={};for(var i in f)for(var j in f[i])c.event.add(this,i,f[i][j],f[i][j].data)}}})}function ia(a,b,d){var f,e,i;b=b&&b[0]?b[0].ownerDocument||b[0]:m;if(a.length===1&&typeof a[0]==="string"&&a[0].length<512&&b===m&&!Ea.test(a[0])&&(c.support.checkClone||!Fa.test(a[0]))){e=
true;if(i=c.fragments[a[0]])if(i!==1)f=i}if(!f){f=b.createDocumentFragment();c.clean(a,b,f,d)}if(e)c.fragments[a[0]]=i?f:1;return{fragment:f,cacheable:e}}function U(a,b){var d={};c.each(Ga.concat.apply([],Ga.slice(0,b)),function(){d[this]=a});return d}function aa(a){return"scrollTo"in a&&a.document?a:a.nodeType===9?a.defaultView||a.parentWindow:false}var c=function(a,b){return new c.fn.init(a,b)},p=E.jQuery,r=E.$,m=E.document,x,v=/^[^<]*(<[\w\W]+>)[^>]*$|^#([\w-]+)$/,w=/^.[^:#\[\.,]*$/,J=/\S/,K=/^(\s|\u00A0)+|(\s|\u00A0)+$/g,
M=/^<(\w+)\s*\/?>(?:<\/\1>)?$/,L=navigator.userAgent,W=false,V=[],qa=!!(typeof require!=="undefined"&&require.def),da,ra=Object.prototype.toString,sa=Object.prototype.hasOwnProperty,ta=Array.prototype.push,ka=Array.prototype.slice,Ha=Array.prototype.indexOf;c.fn=c.prototype={init:function(a,b){var d,f;if(!a)return this;if(a.nodeType){this.context=this[0]=a;this.length=1;return this}if(a==="body"&&!b){this.context=m;this[0]=m.body;this.selector="body";this.length=1;return this}if(typeof a==="string")if((d=
v.exec(a))&&(d[1]||!b))if(d[1]){f=b?b.ownerDocument||b:m;if(a=M.exec(a))if(c.isPlainObject(b)){a=[m.createElement(a[1])];c.fn.attr.call(a,b,true)}else a=[f.createElement(a[1])];else{a=ia([d[1]],[f]);a=(a.cacheable?a.fragment.cloneNode(true):a.fragment).childNodes}return c.merge(this,a)}else{if(b=m.getElementById(d[2])){if(b.id!==d[2])return x.find(a);this.length=1;this[0]=b}this.context=m;this.selector=a;return this}else if(!b&&/^\w+$/.test(a)){this.selector=a;this.context=m;a=m.getElementsByTagName(a);
return c.merge(this,a)}else return!b||b.jquery?(b||x).find(a):c(b).find(a);else if(c.isFunction(a))return x.ready(a);if(a.selector!==A){this.selector=a.selector;this.context=a.context}return c.makeArray(a,this)},selector:"",jquery:"1.4.2",length:0,size:function(){return this.length},toArray:function(){return ka.call(this,0)},get:function(a){return a==null?this.toArray():a<0?this.slice(a)[0]:this[a]},pushStack:function(a,b,d){var f=c();c.isArray(a)?ta.apply(f,a):c.merge(f,a);f.prevObject=this;f.context=
this.context;if(b==="find")f.selector=this.selector+(this.selector?" ":"")+d;else if(b)f.selector=this.selector+"."+b+"("+d+")";return f},each:function(a,b){return c.each(this,a,b)},ready:function(a){c.bindReady();if(c.isReady&&(!qa||require.s.isDone))a.call(m,c);else{V||(V=[]);V.push(a)}return this},eq:function(a){return a===-1?this.slice(a):this.slice(a,+a+1)},first:function(){return this.eq(0)},last:function(){return this.eq(-1)},slice:function(){return this.pushStack(ka.apply(this,arguments),
"slice",ka.call(arguments).join(","))},map:function(a){return this.pushStack(c.map(this,function(b,d){return a.call(b,d,b)}))},end:function(){return this.prevObject||c(null)},push:ta,sort:[].sort,splice:[].splice};c.fn.init.prototype=c.fn;c.extend=c.fn.extend=function(){var a=arguments[0]||{},b=1,d=arguments.length,f=false,e,i,j,q;if(typeof a==="boolean"){f=a;a=arguments[1]||{};b=2}if(typeof a!=="object"&&!c.isFunction(a))a={};if(d===b){a=this;--b}for(;b<d;b++)if((e=arguments[b])!=null)for(i in e){j=
a[i];q=e[i];if(a!==q)if(f&&q&&(c.isPlainObject(q)||c.isArray(q))){j=j&&(c.isPlainObject(j)||c.isArray(j))?j:c.isArray(q)?[]:{};a[i]=c.extend(f,j,q)}else if(q!==A)a[i]=q}return a};c.extend({noConflict:function(a){E.$=r;if(a)E.jQuery=p;return c},isReady:false,ready:function(){if(!c.isReady){if(!m.body)return setTimeout(c.ready,13);c.isReady=true;c.callReady()}},callReady:function(){if(c.isReady&&(!qa||require.s.isDone)){if(V){for(var a,b=0;a=V[b++];)a.call(m,c);V=null}c.fn.triggerHandler&&c(m).triggerHandler("ready")}},
bindReady:function(){if(!W){W=true;if(m.readyState==="complete")return c.ready();if(m.addEventListener){m.addEventListener("DOMContentLoaded",da,false);E.addEventListener("load",c.ready,false)}else if(m.attachEvent){m.attachEvent("onreadystatechange",da);E.attachEvent("onload",c.ready);var a=false;try{a=E.frameElement==null}catch(b){}m.documentElement.doScroll&&a&&C()}}},isFunction:function(a){return ra.call(a)==="[object Function]"},isArray:function(a){return ra.call(a)==="[object Array]"},isPlainObject:function(a){if(!a||
ra.call(a)!=="[object Object]"||a.nodeType||a.setInterval)return false;if(a.constructor&&!sa.call(a,"constructor")&&!sa.call(a.constructor.prototype,"isPrototypeOf"))return false;var b;for(b in a);return b===A||sa.call(a,b)},isEmptyObject:function(a){for(var b in a)return false;return true},error:function(a){throw a;},parseJSON:function(a){if(typeof a!=="string"||!a)return null;a=c.trim(a);if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return E.JSON&&E.JSON.parse?E.JSON.parse(a):(new Function("return "+a))();else c.error("Invalid JSON: "+a)},noop:function(){},globalEval:function(a){if(a&&J.test(a)){var b=m.getElementsByTagName("head")[0]||m.documentElement,d=m.createElement("script");d.type="text/javascript";if(c.support.scriptEval)d.appendChild(m.createTextNode(a));else d.text=a;b.insertBefore(d,b.firstChild);b.removeChild(d)}},nodeName:function(a,b){return a.nodeName&&a.nodeName.toUpperCase()===
b.toUpperCase()},each:function(a,b,d){var f,e=0,i=a.length,j=i===A||c.isFunction(a);if(d)if(j)for(f in a){if(b.apply(a[f],d)===false)break}else for(;e<i;){if(b.apply(a[e++],d)===false)break}else if(j)for(f in a){if(b.call(a[f],f,a[f])===false)break}else for(d=a[0];e<i&&b.call(d,e,d)!==false;d=a[++e]);return a},trim:function(a){return(a||"").replace(K,"")},makeArray:function(a,b){b=b||[];if(a!=null)a.length==null||typeof a==="string"||c.isFunction(a)||typeof a!=="function"&&a.setInterval?ta.call(b,
a):c.merge(b,a);return b},inArray:function(a,b){if(b.indexOf)return b.indexOf(a);for(var d=0,f=b.length;d<f;d++)if(b[d]===a)return d;return-1},merge:function(a,b){var d=a.length,f=0;if(typeof b.length==="number")for(var e=b.length;f<e;f++)a[d++]=b[f];else for(;b[f]!==A;)a[d++]=b[f++];a.length=d;return a},grep:function(a,b,d){for(var f=[],e=0,i=a.length;e<i;e++)!d!==!b(a[e],e)&&f.push(a[e]);return f},map:function(a,b,d){for(var f=[],e,i=0,j=a.length;i<j;i++){e=b(a[i],i,d);if(e!=null)f[f.length]=e}return f.concat.apply([],
f)},guid:1,proxy:function(a,b,d){if(arguments.length===2)if(typeof b==="string"){d=a;a=d[b];b=A}else if(b&&!c.isFunction(b)){d=b;b=A}if(!b&&a)b=function(){return a.apply(d||this,arguments)};if(a)b.guid=a.guid=a.guid||b.guid||c.guid++;return b},uaMatch:function(a){a=a.toLowerCase();a=/(webkit)[ \/]([\w.]+)/.exec(a)||/(opera)(?:.*version)?[ \/]([\w.]+)/.exec(a)||/(msie) ([\w.]+)/.exec(a)||!/compatible/.test(a)&&/(mozilla)(?:.*? rv:([\w.]+))?/.exec(a)||[];return{browser:a[1]||"",version:a[2]||"0"}},
browser:{}});L=c.uaMatch(L);if(L.browser){c.browser[L.browser]=true;c.browser.version=L.version}if(c.browser.webkit)c.browser.safari=true;if(Ha)c.inArray=function(a,b){return Ha.call(b,a)};x=c(m);if(m.addEventListener)da=function(){m.removeEventListener("DOMContentLoaded",da,false);c.ready()};else if(m.attachEvent)da=function(){if(m.readyState==="complete"){m.detachEvent("onreadystatechange",da);c.ready()}};(function(){c.support={};var a=m.documentElement,b=m.createElement("script"),d=m.createElement("div"),
f="script"+R();d.style.display="none";d.innerHTML="   <link/><table></table><a href='/a' style='color:red;float:left;opacity:.55;'>a</a><input type='checkbox'/>";var e=d.getElementsByTagName("*"),i=d.getElementsByTagName("a")[0];if(!(!e||!e.length||!i)){c.support={leadingWhitespace:d.firstChild.nodeType===3,tbody:!d.getElementsByTagName("tbody").length,htmlSerialize:!!d.getElementsByTagName("link").length,style:/red/.test(i.getAttribute("style")),hrefNormalized:i.getAttribute("href")==="/a",opacity:/^0.55$/.test(i.style.opacity),
cssFloat:!!i.style.cssFloat,checkOn:d.getElementsByTagName("input")[0].value==="on",optSelected:m.createElement("select").appendChild(m.createElement("option")).selected,parentNode:d.removeChild(d.appendChild(m.createElement("div"))).parentNode===null,deleteExpando:true,checkClone:false,scriptEval:false,noCloneEvent:true,boxModel:null};b.type="text/javascript";try{b.appendChild(m.createTextNode("window."+f+"=1;"))}catch(j){}a.insertBefore(b,a.firstChild);if(E[f]){c.support.scriptEval=true;delete E[f]}try{delete b.test}catch(q){c.support.deleteExpando=
false}a.removeChild(b);if(d.attachEvent&&d.fireEvent){d.attachEvent("onclick",function k(){c.support.noCloneEvent=false;d.detachEvent("onclick",k)});d.cloneNode(true).fireEvent("onclick")}d=m.createElement("div");d.innerHTML="<input type='radio' name='radiotest' checked='checked'/>";a=m.createDocumentFragment();a.appendChild(d.firstChild);c.support.checkClone=a.cloneNode(true).cloneNode(true).lastChild.checked;c(function(){var k=m.createElement("div");k.style.width=k.style.paddingLeft="1px";m.body.appendChild(k);
c.boxModel=c.support.boxModel=k.offsetWidth===2;m.body.removeChild(k).style.display="none"});a=function(k){var o=m.createElement("div");k="on"+k;var u=k in o;if(!u){o.setAttribute(k,"return;");u=typeof o[k]==="function"}return u};c.support.submitBubbles=a("submit");c.support.changeBubbles=a("change");a=b=d=e=i=null}})();c.props={"for":"htmlFor","class":"className",readonly:"readOnly",maxlength:"maxLength",cellspacing:"cellSpacing",rowspan:"rowSpan",colspan:"colSpan",tabindex:"tabIndex",usemap:"useMap",
frameborder:"frameBorder"};var X="jQuery"+R(),Za=0,Ia={};c.extend({cache:{},expando:X,noData:{embed:true,object:true,applet:true},data:function(a,b,d){if(!(a.nodeName&&c.noData[a.nodeName.toLowerCase()])){a=a==E?Ia:a;var f=a[X],e=c.cache;if(!f&&typeof b==="string"&&d===A)return null;f||(f=++Za);if(typeof b==="object"){a[X]=f;e[f]=c.extend(true,{},b)}else if(!e[f]){a[X]=f;e[f]={}}a=e[f];if(d!==A)a[b]=d;return typeof b==="string"?a[b]:a}},removeData:function(a,b){if(!(a.nodeName&&c.noData[a.nodeName.toLowerCase()])){a=
a==E?Ia:a;var d=a[X],f=c.cache,e=f[d];if(b){if(e){delete e[b];c.isEmptyObject(e)&&c.removeData(a)}}else{if(c.support.deleteExpando)delete a[c.expando];else a.removeAttribute&&a.removeAttribute(c.expando);delete f[d]}}}});c.fn.extend({data:function(a,b){if(typeof a==="undefined"&&this.length)return c.data(this[0]);else if(typeof a==="object")return this.each(function(){c.data(this,a)});var d=a.split(".");d[1]=d[1]?"."+d[1]:"";if(b===A){var f=this.triggerHandler("getData"+d[1]+"!",[d[0]]);if(f===A&&
this.length)f=c.data(this[0],a);return f===A&&d[1]?this.data(d[0]):f}else return this.trigger("setData"+d[1]+"!",[d[0],b]).each(function(){c.data(this,a,b)})},removeData:function(a){return this.each(function(){c.removeData(this,a)})}});c.extend({queue:function(a,b,d){if(a){b=(b||"fx")+"queue";var f=c.data(a,b);if(!d)return f||[];if(!f||c.isArray(d))f=c.data(a,b,c.makeArray(d));else f.push(d);return f}},dequeue:function(a,b){b=b||"fx";var d=c.queue(a,b),f=d.shift();if(f==="inprogress")f=d.shift();
if(f){b==="fx"&&d.unshift("inprogress");f.call(a,function(){c.dequeue(a,b)})}}});c.fn.extend({queue:function(a,b){if(typeof a!=="string"){b=a;a="fx"}if(b===A)return c.queue(this[0],a);return this.each(function(){var d=c.queue(this,a,b);a==="fx"&&d[0]!=="inprogress"&&c.dequeue(this,a)})},dequeue:function(a){return this.each(function(){c.dequeue(this,a)})},delay:function(a,b){a=c.fx?c.fx.speeds[a]||a:a;b=b||"fx";return this.queue(b,function(){var d=this;setTimeout(function(){c.dequeue(d,b)},a)})},clearQueue:function(a){return this.queue(a||
"fx",[])}});var Ja=/[\n\t]/g,ua=/\s+/,$a=/\r/g,ab=/href|src|style/,bb=/(button|input)/i,cb=/(button|input|object|select|textarea)/i,db=/^(a|area)$/i,Ka=/radio|checkbox/;c.fn.extend({attr:function(a,b){return ga(this,a,b,true,c.attr)},removeAttr:function(a){return this.each(function(){c.attr(this,a,"");this.nodeType===1&&this.removeAttribute(a)})},addClass:function(a){if(c.isFunction(a))return this.each(function(o){var u=c(this);u.addClass(a.call(this,o,u.attr("class")))});if(a&&typeof a==="string")for(var b=
(a||"").split(ua),d=0,f=this.length;d<f;d++){var e=this[d];if(e.nodeType===1)if(e.className){for(var i=" "+e.className+" ",j=e.className,q=0,k=b.length;q<k;q++)if(i.indexOf(" "+b[q]+" ")<0)j+=" "+b[q];e.className=c.trim(j)}else e.className=a}return this},removeClass:function(a){if(c.isFunction(a))return this.each(function(k){var o=c(this);o.removeClass(a.call(this,k,o.attr("class")))});if(a&&typeof a==="string"||a===A)for(var b=(a||"").split(ua),d=0,f=this.length;d<f;d++){var e=this[d];if(e.nodeType===
1&&e.className)if(a){for(var i=(" "+e.className+" ").replace(Ja," "),j=0,q=b.length;j<q;j++)i=i.replace(" "+b[j]+" "," ");e.className=c.trim(i)}else e.className=""}return this},toggleClass:function(a,b){var d=typeof a,f=typeof b==="boolean";if(c.isFunction(a))return this.each(function(e){var i=c(this);i.toggleClass(a.call(this,e,i.attr("class"),b),b)});return this.each(function(){if(d==="string")for(var e,i=0,j=c(this),q=b,k=a.split(ua);e=k[i++];){q=f?q:!j.hasClass(e);j[q?"addClass":"removeClass"](e)}else if(d===
"undefined"||d==="boolean"){this.className&&c.data(this,"__className__",this.className);this.className=this.className||a===false?"":c.data(this,"__className__")||""}})},hasClass:function(a){a=" "+a+" ";for(var b=0,d=this.length;b<d;b++)if((" "+this[b].className+" ").replace(Ja," ").indexOf(a)>-1)return true;return false},val:function(a){if(a===A){var b=this[0];if(b){if(c.nodeName(b,"option"))return(b.attributes.value||{}).specified?b.value:b.text;if(c.nodeName(b,"select")){var d=b.selectedIndex,f=
[],e=b.options;b=b.type==="select-one";if(d<0)return null;var i=b?d:0;for(d=b?d+1:e.length;i<d;i++){var j=e[i];if(j.selected){a=c(j).val();if(b)return a;f.push(a)}}return f}if(Ka.test(b.type)&&!c.support.checkOn)return b.getAttribute("value")===null?"on":b.value;return(b.value||"").replace($a,"")}return A}var q=c.isFunction(a);return this.each(function(k){var o=c(this),u=a;if(this.nodeType===1){if(q)u=a.call(this,k,o.val());if(typeof u==="number")u+="";if(c.isArray(u)&&Ka.test(this.type))this.checked=
c.inArray(o.val(),u)>=0;else if(c.nodeName(this,"select")){var z=c.makeArray(u);c("option",this).each(function(){this.selected=c.inArray(c(this).val(),z)>=0});if(!z.length)this.selectedIndex=-1}else this.value=u}})}});c.extend({attrFn:{val:true,css:true,html:true,text:true,data:true,width:true,height:true,offset:true},attr:function(a,b,d,f){if(!a||a.nodeType===3||a.nodeType===8)return A;if(f&&b in c.attrFn)return c(a)[b](d);f=a.nodeType!==1||!c.isXMLDoc(a);var e=d!==A;b=f&&c.props[b]||b;if(a.nodeType===
1){var i=ab.test(b);if(b in a&&f&&!i){if(e){b==="type"&&bb.test(a.nodeName)&&a.parentNode&&c.error("type property can't be changed");a[b]=d}if(c.nodeName(a,"form")&&a.getAttributeNode(b))return a.getAttributeNode(b).nodeValue;if(b==="tabIndex")return(b=a.getAttributeNode("tabIndex"))&&b.specified?b.value:cb.test(a.nodeName)||db.test(a.nodeName)&&a.href?0:A;return a[b]}if(!c.support.style&&f&&b==="style"){if(e)a.style.cssText=""+d;return a.style.cssText}e&&a.setAttribute(b,""+d);a=!c.support.hrefNormalized&&
f&&i?a.getAttribute(b,2):a.getAttribute(b);return a===null?A:a}return c.style(a,b,d)}});var ja=/\.(.*)$/,eb=function(a){return a.replace(/[^\w\s\.\|`]/g,function(b){return"\\"+b})};c.event={add:function(a,b,d,f){if(!(a.nodeType===3||a.nodeType===8)){if(a.setInterval&&a!==E&&!a.frameElement)a=E;var e,i;if(d.handler){e=d;d=e.handler}if(!d.guid)d.guid=c.guid++;if(i=c.data(a)){var j=i.events=i.events||{},q=i.handle;if(!q)i.handle=q=function(){return typeof c!=="undefined"&&!c.event.triggered?c.event.handle.apply(q.elem,
arguments):A};q.elem=a;b=b.split(" ");for(var k,o=0,u;k=b[o++];){i=e?c.extend({},e):{handler:d,data:f};if(k.indexOf(".")>-1){u=k.split(".");k=u.shift();i.namespace=u.slice(0).sort().join(".")}else{u=[];i.namespace=""}i.type=k;i.guid=d.guid;var z=j[k],G=c.event.special[k]||{};if(!z){z=j[k]=[];if(!G.setup||G.setup.call(a,f,u,q)===false)if(a.addEventListener)a.addEventListener(k,q,false);else a.attachEvent&&a.attachEvent("on"+k,q)}if(G.add){G.add.call(a,i);if(!i.handler.guid)i.handler.guid=d.guid}z.push(i);
c.event.global[k]=true}a=null}}},global:{},remove:function(a,b,d,f){if(!(a.nodeType===3||a.nodeType===8)){var e,i=0,j,q,k,o,u,z,G=c.data(a),I=G&&G.events;if(G&&I){if(b&&b.type){d=b.handler;b=b.type}if(!b||typeof b==="string"&&b.charAt(0)==="."){b=b||"";for(e in I)c.event.remove(a,e+b)}else{for(b=b.split(" ");e=b[i++];){o=e;j=e.indexOf(".")<0;q=[];if(!j){q=e.split(".");e=q.shift();k=new RegExp("(^|\\.)"+c.map(q.slice(0).sort(),eb).join("\\.(?:.*\\.)?")+"(\\.|$)")}if(u=I[e])if(d){o=c.event.special[e]||
{};for(H=f||0;H<u.length;H++){z=u[H];if(d.guid===z.guid){if(j||k.test(z.namespace)){f==null&&u.splice(H--,1);o.remove&&o.remove.call(a,z)}if(f!=null)break}}if(u.length===0||f!=null&&u.length===1){if(!o.teardown||o.teardown.call(a,q)===false)La(a,e,G.handle);delete I[e]}}else for(var H=0;H<u.length;H++){z=u[H];if(j||k.test(z.namespace)){c.event.remove(a,o,z.handler,H);u.splice(H--,1)}}}if(c.isEmptyObject(I)){if(b=G.handle)b.elem=null;delete G.events;delete G.handle;c.isEmptyObject(G)&&c.removeData(a)}}}}},
trigger:function(a,b,d,f){var e=a.type||a;if(!f){a=typeof a==="object"?a[X]?a:c.extend(c.Event(e),a):c.Event(e);if(e.indexOf("!")>=0){a.type=e=e.slice(0,-1);a.exclusive=true}if(!d){a.stopPropagation();c.event.global[e]&&c.each(c.cache,function(){this.events&&this.events[e]&&c.event.trigger(a,b,this.handle.elem)})}if(!d||d.nodeType===3||d.nodeType===8)return A;a.result=A;a.target=d;b=c.makeArray(b);b.unshift(a)}a.currentTarget=d;(f=c.data(d,"handle"))&&f.apply(d,b);f=d.parentNode||d.ownerDocument;
try{if(!(d&&d.nodeName&&c.noData[d.nodeName.toLowerCase()]))if(d["on"+e]&&d["on"+e].apply(d,b)===false)a.result=false}catch(i){}if(!a.isPropagationStopped()&&f)c.event.trigger(a,b,f,true);else if(!a.isDefaultPrevented()){f=a.target;var j,q=c.nodeName(f,"a")&&e==="click",k=c.event.special[e]||{};if((!k._default||k._default.call(d,a)===false)&&!q&&!(f&&f.nodeName&&c.noData[f.nodeName.toLowerCase()])){try{if(f[e]){if(j=f["on"+e])f["on"+e]=null;c.event.triggered=true;f[e]()}}catch(o){}if(j)f["on"+e]=
j;c.event.triggered=false}}},handle:function(a){var b,d,f,e;a=arguments[0]=c.event.fix(a||E.event);a.currentTarget=this;b=a.type.indexOf(".")<0&&!a.exclusive;if(!b){d=a.type.split(".");a.type=d.shift();f=new RegExp("(^|\\.)"+d.slice(0).sort().join("\\.(?:.*\\.)?")+"(\\.|$)")}e=c.data(this,"events");d=e[a.type];if(e&&d){d=d.slice(0);e=0;for(var i=d.length;e<i;e++){var j=d[e];if(b||f.test(j.namespace)){a.handler=j.handler;a.data=j.data;a.handleObj=j;j=j.handler.apply(this,arguments);if(j!==A){a.result=
j;if(j===false){a.preventDefault();a.stopPropagation()}}if(a.isImmediatePropagationStopped())break}}}return a.result},props:"altKey attrChange attrName bubbles button cancelable charCode clientX clientY ctrlKey currentTarget data detail eventPhase fromElement handler keyCode layerX layerY metaKey newValue offsetX offsetY originalTarget pageX pageY prevValue relatedNode relatedTarget screenX screenY shiftKey srcElement target toElement view wheelDelta which".split(" "),fix:function(a){if(a[X])return a;
var b=a;a=c.Event(b);for(var d=this.props.length,f;d;){f=this.props[--d];a[f]=b[f]}if(!a.target)a.target=a.srcElement||m;if(a.target.nodeType===3)a.target=a.target.parentNode;if(!a.relatedTarget&&a.fromElement)a.relatedTarget=a.fromElement===a.target?a.toElement:a.fromElement;if(a.pageX==null&&a.clientX!=null){b=m.documentElement;d=m.body;a.pageX=a.clientX+(b&&b.scrollLeft||d&&d.scrollLeft||0)-(b&&b.clientLeft||d&&d.clientLeft||0);a.pageY=a.clientY+(b&&b.scrollTop||d&&d.scrollTop||0)-(b&&b.clientTop||
d&&d.clientTop||0)}if(!a.which&&(a.charCode||a.charCode===0?a.charCode:a.keyCode))a.which=a.charCode||a.keyCode;if(!a.metaKey&&a.ctrlKey)a.metaKey=a.ctrlKey;if(!a.which&&a.button!==A)a.which=a.button&1?1:a.button&2?3:a.button&4?2:0;return a},guid:1E8,proxy:c.proxy,special:{ready:{setup:c.bindReady,teardown:c.noop},live:{add:function(a){c.event.add(this,a.origType,c.extend({},a,{handler:ha}))},remove:function(a){var b=true,d=a.origType.replace(ja,"");c.each(c.data(this,"events").live||[],function(){if(d===
this.origType.replace(ja,""))return b=false});b&&c.event.remove(this,a.origType,ha)}},beforeunload:{setup:function(a,b,d){if(this.setInterval)this.onbeforeunload=d;return false},teardown:function(a,b){if(this.onbeforeunload===b)this.onbeforeunload=null}}}};var La=m.removeEventListener?function(a,b,d){a.removeEventListener(b,d,false)}:function(a,b,d){a.detachEvent("on"+b,d)};c.Event=function(a){if(!this.preventDefault)return new c.Event(a);if(a&&a.type){this.originalEvent=a;this.type=a.type}else this.type=
a;this.timeStamp=R();this[X]=true};c.Event.prototype={preventDefault:function(){this.isDefaultPrevented=ba;var a=this.originalEvent;if(a){a.preventDefault&&a.preventDefault();a.returnValue=false}},stopPropagation:function(){this.isPropagationStopped=ba;var a=this.originalEvent;if(a){a.stopPropagation&&a.stopPropagation();a.cancelBubble=true}},stopImmediatePropagation:function(){this.isImmediatePropagationStopped=ba;this.stopPropagation()},isDefaultPrevented:$,isPropagationStopped:$,isImmediatePropagationStopped:$};
var Ma=function(a){var b=a.relatedTarget;try{for(;b&&b!==this;)b=b.parentNode;if(b!==this){a.type=a.data;c.event.handle.apply(this,arguments)}}catch(d){}},Na=function(a){a.type=a.data;c.event.handle.apply(this,arguments)};c.each({mouseenter:"mouseover",mouseleave:"mouseout"},function(a,b){c.event.special[a]={setup:function(d){c.event.add(this,b,d&&d.selector?Na:Ma,a)},teardown:function(d){c.event.remove(this,b,d&&d.selector?Na:Ma)}}});if(!c.support.submitBubbles)c.event.special.submit={setup:function(){if(this.nodeName.toLowerCase()!==
"form"){c.event.add(this,"click.specialSubmit",function(a){var b=a.target,d=b.type;if((d==="submit"||d==="image")&&c(b).closest("form").length)return ca("submit",this,arguments)});c.event.add(this,"keypress.specialSubmit",function(a){var b=a.target,d=b.type;if((d==="text"||d==="password")&&c(b).closest("form").length&&a.keyCode===13)return ca("submit",this,arguments)})}else return false},teardown:function(){c.event.remove(this,".specialSubmit")}};if(!c.support.changeBubbles){var va=/textarea|input|select/i,
wa,Oa=function(a){var b=a.type,d=a.value;if(b==="radio"||b==="checkbox")d=a.checked;else if(b==="select-multiple")d=a.selectedIndex>-1?c.map(a.options,function(f){return f.selected}).join("-"):"";else if(a.nodeName.toLowerCase()==="select")d=a.selectedIndex;return d},xa=function(a,b){var d=a.target,f,e;if(!(!va.test(d.nodeName)||d.readOnly)){f=c.data(d,"_change_data");e=Oa(d);if(a.type!=="focusout"||d.type!=="radio")c.data(d,"_change_data",e);if(!(f===A||e===f))if(f!=null||e){a.type="change";return c.event.trigger(a,
b,d)}}};c.event.special.change={filters:{focusout:xa,click:function(a){var b=a.target,d=b.type;if(d==="radio"||d==="checkbox"||b.nodeName.toLowerCase()==="select")return xa.call(this,a)},keydown:function(a){var b=a.target,d=b.type;if(a.keyCode===13&&b.nodeName.toLowerCase()!=="textarea"||a.keyCode===32&&(d==="checkbox"||d==="radio")||d==="select-multiple")return xa.call(this,a)},beforeactivate:function(a){a=a.target;c.data(a,"_change_data",Oa(a))}},setup:function(){if(this.type==="file")return false;
for(var a in wa)c.event.add(this,a+".specialChange",wa[a]);return va.test(this.nodeName)},teardown:function(){c.event.remove(this,".specialChange");return va.test(this.nodeName)}};wa=c.event.special.change.filters}m.addEventListener&&c.each({focus:"focusin",blur:"focusout"},function(a,b){function d(f){f=c.event.fix(f);f.type=b;return c.event.handle.call(this,f)}c.event.special[b]={setup:function(){this.addEventListener(a,d,true)},teardown:function(){this.removeEventListener(a,d,true)}}});c.each(["bind",
"one"],function(a,b){c.fn[b]=function(d,f,e){if(typeof d==="object"){for(var i in d)this[b](i,f,d[i],e);return this}if(c.isFunction(f)){e=f;f=A}var j=b==="one"?c.proxy(e,function(k){c(this).unbind(k,j);return e.apply(this,arguments)}):e;if(d==="unload"&&b!=="one")this.one(d,f,e);else{i=0;for(var q=this.length;i<q;i++)c.event.add(this[i],d,j,f)}return this}});c.fn.extend({unbind:function(a,b){if(typeof a==="object"&&!a.preventDefault)for(var d in a)this.unbind(d,a[d]);else{d=0;for(var f=this.length;d<
f;d++)c.event.remove(this[d],a,b)}return this},delegate:function(a,b,d,f){return this.live(b,d,f,a)},undelegate:function(a,b,d){return arguments.length===0?this.unbind("live"):this.die(b,null,d,a)},trigger:function(a,b){return this.each(function(){c.event.trigger(a,b,this)})},triggerHandler:function(a,b){if(this[0]){a=c.Event(a);a.preventDefault();a.stopPropagation();c.event.trigger(a,b,this[0]);return a.result}},toggle:function(a){for(var b=arguments,d=1;d<b.length;)c.proxy(a,b[d++]);return this.click(c.proxy(a,
function(f){var e=(c.data(this,"lastToggle"+a.guid)||0)%d;c.data(this,"lastToggle"+a.guid,e+1);f.preventDefault();return b[e].apply(this,arguments)||false}))},hover:function(a,b){return this.mouseenter(a).mouseleave(b||a)}});var Pa={focus:"focusin",blur:"focusout",mouseenter:"mouseover",mouseleave:"mouseout"};c.each(["live","die"],function(a,b){c.fn[b]=function(d,f,e,i){var j,q=0,k,o,u=i||this.selector,z=i?this:c(this.context);if(c.isFunction(f)){e=f;f=A}for(d=(d||"").split(" ");(j=d[q++])!=null;){i=
ja.exec(j);k="";if(i){k=i[0];j=j.replace(ja,"")}if(j==="hover")d.push("mouseenter"+k,"mouseleave"+k);else{o=j;if(j==="focus"||j==="blur"){d.push(Pa[j]+k);j+=k}else j=(Pa[j]||j)+k;b==="live"?z.each(function(){c.event.add(this,S(j,u),{data:f,selector:u,handler:e,origType:j,origHandler:e,preType:o})}):z.unbind(S(j,u),e)}}return this}});c.each("blur focus focusin focusout load resize scroll unload click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave change select submit keydown keypress keyup error".split(" "),
function(a,b){c.fn[b]=function(d){return d?this.bind(b,d):this.trigger(b)};if(c.attrFn)c.attrFn[b]=true});E.attachEvent&&!E.addEventListener&&E.attachEvent("onunload",function(){for(var a in c.cache)if(c.cache[a].handle)try{c.event.remove(c.cache[a].handle.elem)}catch(b){}});(function(){function a(g){for(var h="",l,n=0;g[n];n++){l=g[n];if(l.nodeType===3||l.nodeType===4)h+=l.nodeValue;else if(l.nodeType!==8)h+=a(l.childNodes)}return h}function b(g,h,l,n,t,s){t=0;for(var B=n.length;t<B;t++){var y=n[t];
if(y){y=y[g];for(var F=false;y;){if(y.sizcache===l){F=n[y.sizset];break}if(y.nodeType===1&&!s){y.sizcache=l;y.sizset=t}if(y.nodeName.toLowerCase()===h){F=y;break}y=y[g]}n[t]=F}}}function d(g,h,l,n,t,s){t=0;for(var B=n.length;t<B;t++){var y=n[t];if(y){y=y[g];for(var F=false;y;){if(y.sizcache===l){F=n[y.sizset];break}if(y.nodeType===1){if(!s){y.sizcache=l;y.sizset=t}if(typeof h!=="string"){if(y===h){F=true;break}}else if(k.filter(h,[y]).length>0){F=y;break}}y=y[g]}n[t]=F}}}var f=/((?:\((?:\([^()]+\)|[^()]+)+\)|\[(?:\[[^[\]]*\]|['"][^'"]*['"]|[^[\]'"]+)+\]|\\.|[^ >+~,(\[\\]+)+|[>+~])(\s*,\s*)?((?:.|\r|\n)*)/g,
e=0,i=Object.prototype.toString,j=false,q=true;[0,0].sort(function(){q=false;return 0});var k=function(g,h,l,n){l=l||[];var t=h=h||m;if(h.nodeType!==1&&h.nodeType!==9)return[];if(!g||typeof g!=="string")return l;for(var s=[],B,y,F,la,Y=true,ea=D(h),Z=g;(f.exec(""),B=f.exec(Z))!==null;){Z=B[3];s.push(B[1]);if(B[2]){la=B[3];break}}if(s.length>1&&u.exec(g))if(s.length===2&&o.relative[s[0]])y=ya(s[0]+s[1],h);else for(y=o.relative[s[0]]?[h]:k(s.shift(),h);s.length;){g=s.shift();if(o.relative[g])g+=s.shift();
y=ya(g,y)}else{if(!n&&s.length>1&&h.nodeType===9&&!ea&&o.match.ID.test(s[0])&&!o.match.ID.test(s[s.length-1])){B=k.find(s.shift(),h,ea);h=B.expr?k.filter(B.expr,B.set)[0]:B.set[0]}if(h){B=n?{expr:s.pop(),set:G(n)}:k.find(s.pop(),s.length===1&&(s[0]==="~"||s[0]==="+")&&h.parentNode?h.parentNode:h,ea);y=B.expr?k.filter(B.expr,B.set):B.set;if(s.length>0)F=G(y);else Y=false;for(;s.length;){var O=s.pop();B=O;if(o.relative[O])B=s.pop();else O="";if(B==null)B=h;o.relative[O](F,B,ea)}}else F=[]}F||(F=y);
F||k.error(O||g);if(i.call(F)==="[object Array]")if(Y)if(h&&h.nodeType===1)for(g=0;F[g]!=null;g++){if(F[g]&&(F[g]===true||F[g].nodeType===1&&P(h,F[g])))l.push(y[g])}else for(g=0;F[g]!=null;g++)F[g]&&F[g].nodeType===1&&l.push(y[g]);else l.push.apply(l,F);else G(F,l);if(la){k(la,t,l,n);k.uniqueSort(l)}return l};k.uniqueSort=function(g){if(H){j=q;g.sort(H);if(j)for(var h=1;h<g.length;h++)g[h]===g[h-1]&&g.splice(h--,1)}return g};k.matches=function(g,h){return k(g,null,null,h)};k.find=function(g,h,l){var n,
t;if(!g)return[];for(var s=0,B=o.order.length;s<B;s++){var y=o.order[s];if(t=o.leftMatch[y].exec(g)){var F=t[1];t.splice(1,1);if(F.substr(F.length-1)!=="\\"){t[1]=(t[1]||"").replace(/\\/g,"");n=o.find[y](t,h,l);if(n!=null){g=g.replace(o.match[y],"");break}}}}n||(n=h.getElementsByTagName("*"));return{set:n,expr:g}};k.filter=function(g,h,l,n){for(var t=g,s=[],B=h,y,F,la=h&&h[0]&&D(h[0]);g&&h.length;){for(var Y in o.filter)if((y=o.leftMatch[Y].exec(g))!=null&&y[2]){var ea=o.filter[Y],Z,O;O=y[1];F=false;
y.splice(1,1);if(O.substr(O.length-1)!=="\\"){if(B===s)s=[];if(o.preFilter[Y])if(y=o.preFilter[Y](y,B,l,s,n,la)){if(y===true)continue}else F=Z=true;if(y)for(var na=0;(O=B[na])!=null;na++)if(O){Z=ea(O,y,na,B);var Qa=n^!!Z;if(l&&Z!=null)if(Qa)F=true;else B[na]=false;else if(Qa){s.push(O);F=true}}if(Z!==A){l||(B=s);g=g.replace(o.match[Y],"");if(!F)return[];break}}}if(g===t)if(F==null)k.error(g);else break;t=g}return B};k.error=function(g){throw"Syntax error, unrecognized expression: "+g;};var o=k.selectors=
{order:["ID","NAME","TAG"],match:{ID:/#((?:[\w\u00c0-\uFFFF-]|\\.)+)/,CLASS:/\.((?:[\w\u00c0-\uFFFF-]|\\.)+)/,NAME:/\[name=['"]*((?:[\w\u00c0-\uFFFF-]|\\.)+)['"]*\]/,ATTR:/\[\s*((?:[\w\u00c0-\uFFFF-]|\\.)+)\s*(?:(\S?=)\s*(['"]*)(.*?)\3|)\s*\]/,TAG:/^((?:[\w\u00c0-\uFFFF\*-]|\\.)+)/,CHILD:/:(only|nth|last|first)-child(?:\((even|odd|[\dn+-]*)\))?/,POS:/:(nth|eq|gt|lt|first|last|even|odd)(?:\((\d*)\))?(?=[^-]|$)/,PSEUDO:/:((?:[\w\u00c0-\uFFFF-]|\\.)+)(?:\((['"]?)((?:\([^\)]+\)|[^\(\)]*)+)\2\))?/},leftMatch:{},
attrMap:{"class":"className","for":"htmlFor"},attrHandle:{href:function(g){return g.getAttribute("href")}},relative:{"+":function(g,h){var l=typeof h==="string",n=l&&!/\W/.test(h);l=l&&!n;if(n)h=h.toLowerCase();n=0;for(var t=g.length,s;n<t;n++)if(s=g[n]){for(;(s=s.previousSibling)&&s.nodeType!==1;);g[n]=l||s&&s.nodeName.toLowerCase()===h?s||false:s===h}l&&k.filter(h,g,true)},">":function(g,h){var l=typeof h==="string";if(l&&!/\W/.test(h)){h=h.toLowerCase();for(var n=0,t=g.length;n<t;n++){var s=g[n];
if(s){l=s.parentNode;g[n]=l.nodeName.toLowerCase()===h?l:false}}}else{n=0;for(t=g.length;n<t;n++)if(s=g[n])g[n]=l?s.parentNode:s.parentNode===h;l&&k.filter(h,g,true)}},"":function(g,h,l){var n=e++,t=d;if(typeof h==="string"&&!/\W/.test(h)){var s=h=h.toLowerCase();t=b}t("parentNode",h,n,g,s,l)},"~":function(g,h,l){var n=e++,t=d;if(typeof h==="string"&&!/\W/.test(h)){var s=h=h.toLowerCase();t=b}t("previousSibling",h,n,g,s,l)}},find:{ID:function(g,h,l){if(typeof h.getElementById!=="undefined"&&!l)return(g=
h.getElementById(g[1]))?[g]:[]},NAME:function(g,h){if(typeof h.getElementsByName!=="undefined"){var l=[];h=h.getElementsByName(g[1]);for(var n=0,t=h.length;n<t;n++)h[n].getAttribute("name")===g[1]&&l.push(h[n]);return l.length===0?null:l}},TAG:function(g,h){return h.getElementsByTagName(g[1])}},preFilter:{CLASS:function(g,h,l,n,t,s){g=" "+g[1].replace(/\\/g,"")+" ";if(s)return g;s=0;for(var B;(B=h[s])!=null;s++)if(B)if(t^(B.className&&(" "+B.className+" ").replace(/[\t\n]/g," ").indexOf(g)>=0))l||
n.push(B);else if(l)h[s]=false;return false},ID:function(g){return g[1].replace(/\\/g,"")},TAG:function(g){return g[1].toLowerCase()},CHILD:function(g){if(g[1]==="nth"){var h=/(-?)(\d*)n((?:\+|-)?\d*)/.exec(g[2]==="even"&&"2n"||g[2]==="odd"&&"2n+1"||!/\D/.test(g[2])&&"0n+"+g[2]||g[2]);g[2]=h[1]+(h[2]||1)-0;g[3]=h[3]-0}g[0]=e++;return g},ATTR:function(g,h,l,n,t,s){h=g[1].replace(/\\/g,"");if(!s&&o.attrMap[h])g[1]=o.attrMap[h];if(g[2]==="~=")g[4]=" "+g[4]+" ";return g},PSEUDO:function(g,h,l,n,t){if(g[1]===
"not")if((f.exec(g[3])||"").length>1||/^\w/.test(g[3]))g[3]=k(g[3],null,null,h);else{g=k.filter(g[3],h,l,true^t);l||n.push.apply(n,g);return false}else if(o.match.POS.test(g[0])||o.match.CHILD.test(g[0]))return true;return g},POS:function(g){g.unshift(true);return g}},filters:{enabled:function(g){return g.disabled===false&&g.type!=="hidden"},disabled:function(g){return g.disabled===true},checked:function(g){return g.checked===true},selected:function(g){return g.selected===true},parent:function(g){return!!g.firstChild},
empty:function(g){return!g.firstChild},has:function(g,h,l){return!!k(l[3],g).length},header:function(g){return/h\d/i.test(g.nodeName)},text:function(g){return"text"===g.type},radio:function(g){return"radio"===g.type},checkbox:function(g){return"checkbox"===g.type},file:function(g){return"file"===g.type},password:function(g){return"password"===g.type},submit:function(g){return"submit"===g.type},image:function(g){return"image"===g.type},reset:function(g){return"reset"===g.type},button:function(g){return"button"===
g.type||g.nodeName.toLowerCase()==="button"},input:function(g){return/input|select|textarea|button/i.test(g.nodeName)}},setFilters:{first:function(g,h){return h===0},last:function(g,h,l,n){return h===n.length-1},even:function(g,h){return h%2===0},odd:function(g,h){return h%2===1},lt:function(g,h,l){return h<l[3]-0},gt:function(g,h,l){return h>l[3]-0},nth:function(g,h,l){return l[3]-0===h},eq:function(g,h,l){return l[3]-0===h}},filter:{PSEUDO:function(g,h,l,n){var t=h[1],s=o.filters[t];if(s)return s(g,
l,h,n);else if(t==="contains")return(g.textContent||g.innerText||a([g])||"").indexOf(h[3])>=0;else if(t==="not"){h=h[3];l=0;for(n=h.length;l<n;l++)if(h[l]===g)return false;return true}else k.error("Syntax error, unrecognized expression: "+t)},CHILD:function(g,h){var l=h[1],n=g;switch(l){case "only":case "first":for(;n=n.previousSibling;)if(n.nodeType===1)return false;if(l==="first")return true;n=g;case "last":for(;n=n.nextSibling;)if(n.nodeType===1)return false;return true;case "nth":l=h[2];var t=
h[3];if(l===1&&t===0)return true;h=h[0];var s=g.parentNode;if(s&&(s.sizcache!==h||!g.nodeIndex)){var B=0;for(n=s.firstChild;n;n=n.nextSibling)if(n.nodeType===1)n.nodeIndex=++B;s.sizcache=h}g=g.nodeIndex-t;return l===0?g===0:g%l===0&&g/l>=0}},ID:function(g,h){return g.nodeType===1&&g.getAttribute("id")===h},TAG:function(g,h){return h==="*"&&g.nodeType===1||g.nodeName.toLowerCase()===h},CLASS:function(g,h){return(" "+(g.className||g.getAttribute("class"))+" ").indexOf(h)>-1},ATTR:function(g,h){var l=
h[1];g=o.attrHandle[l]?o.attrHandle[l](g):g[l]!=null?g[l]:g.getAttribute(l);l=g+"";var n=h[2];h=h[4];return g==null?n==="!=":n==="="?l===h:n==="*="?l.indexOf(h)>=0:n==="~="?(" "+l+" ").indexOf(h)>=0:!h?l&&g!==false:n==="!="?l!==h:n==="^="?l.indexOf(h)===0:n==="$="?l.substr(l.length-h.length)===h:n==="|="?l===h||l.substr(0,h.length+1)===h+"-":false},POS:function(g,h,l,n){var t=o.setFilters[h[2]];if(t)return t(g,l,h,n)}}},u=o.match.POS;for(var z in o.match){o.match[z]=new RegExp(o.match[z].source+/(?![^\[]*\])(?![^\(]*\))/.source);
o.leftMatch[z]=new RegExp(/(^(?:.|\r|\n)*?)/.source+o.match[z].source.replace(/\\(\d+)/g,function(g,h){return"\\"+(h-0+1)}))}var G=function(g,h){g=Array.prototype.slice.call(g,0);if(h){h.push.apply(h,g);return h}return g};try{Array.prototype.slice.call(m.documentElement.childNodes,0)}catch(I){G=function(g,h){h=h||[];if(i.call(g)==="[object Array]")Array.prototype.push.apply(h,g);else if(typeof g.length==="number")for(var l=0,n=g.length;l<n;l++)h.push(g[l]);else for(l=0;g[l];l++)h.push(g[l]);return h}}var H;
if(m.documentElement.compareDocumentPosition)H=function(g,h){if(!g.compareDocumentPosition||!h.compareDocumentPosition){if(g==h)j=true;return g.compareDocumentPosition?-1:1}g=g.compareDocumentPosition(h)&4?-1:g===h?0:1;if(g===0)j=true;return g};else if("sourceIndex"in m.documentElement)H=function(g,h){if(!g.sourceIndex||!h.sourceIndex){if(g==h)j=true;return g.sourceIndex?-1:1}g=g.sourceIndex-h.sourceIndex;if(g===0)j=true;return g};else if(m.createRange)H=function(g,h){if(!g.ownerDocument||!h.ownerDocument){if(g==
h)j=true;return g.ownerDocument?-1:1}var l=g.ownerDocument.createRange(),n=h.ownerDocument.createRange();l.setStart(g,0);l.setEnd(g,0);n.setStart(h,0);n.setEnd(h,0);g=l.compareBoundaryPoints(Range.START_TO_END,n);if(g===0)j=true;return g};(function(){var g=m.createElement("div"),h="script"+(new Date).getTime();g.innerHTML="<a name='"+h+"'/>";var l=m.documentElement;l.insertBefore(g,l.firstChild);if(m.getElementById(h)){o.find.ID=function(n,t,s){if(typeof t.getElementById!=="undefined"&&!s)return(t=
t.getElementById(n[1]))?t.id===n[1]||typeof t.getAttributeNode!=="undefined"&&t.getAttributeNode("id").nodeValue===n[1]?[t]:A:[]};o.filter.ID=function(n,t){var s=typeof n.getAttributeNode!=="undefined"&&n.getAttributeNode("id");return n.nodeType===1&&s&&s.nodeValue===t}}l.removeChild(g);l=g=null})();(function(){var g=m.createElement("div");g.appendChild(m.createComment(""));if(g.getElementsByTagName("*").length>0)o.find.TAG=function(h,l){l=l.getElementsByTagName(h[1]);if(h[1]==="*"){h=[];for(var n=
0;l[n];n++)l[n].nodeType===1&&h.push(l[n]);l=h}return l};g.innerHTML="<a href='#'></a>";if(g.firstChild&&typeof g.firstChild.getAttribute!=="undefined"&&g.firstChild.getAttribute("href")!=="#")o.attrHandle.href=function(h){return h.getAttribute("href",2)};g=null})();m.querySelectorAll&&function(){var g=k,h=m.createElement("div");h.innerHTML="<p class='TEST'></p>";if(!(h.querySelectorAll&&h.querySelectorAll(".TEST").length===0)){k=function(n,t,s,B){t=t||m;if(!B&&t.nodeType===9&&!D(t))try{return G(t.querySelectorAll(n),
s)}catch(y){}return g(n,t,s,B)};for(var l in g)k[l]=g[l];h=null}}();(function(){var g=m.createElement("div");g.innerHTML="<div class='test e'></div><div class='test'></div>";if(!(!g.getElementsByClassName||g.getElementsByClassName("e").length===0)){g.lastChild.className="e";if(g.getElementsByClassName("e").length!==1){o.order.splice(1,0,"CLASS");o.find.CLASS=function(h,l,n){if(typeof l.getElementsByClassName!=="undefined"&&!n)return l.getElementsByClassName(h[1])};g=null}}})();var P=m.compareDocumentPosition?
function(g,h){return!!(g.compareDocumentPosition(h)&16)}:function(g,h){return g!==h&&(g.contains?g.contains(h):true)},D=function(g){return(g=(g?g.ownerDocument||g:0).documentElement)?g.nodeName!=="HTML":false},ya=function(g,h){var l=[],n="",t;for(h=h.nodeType?[h]:h;t=o.match.PSEUDO.exec(g);){n+=t[0];g=g.replace(o.match.PSEUDO,"")}g=o.relative[g]?g+"*":g;t=0;for(var s=h.length;t<s;t++)k(g,h[t],l);return k.filter(n,l)};c.find=k;c.expr=k.selectors;c.expr[":"]=c.expr.filters;c.unique=k.uniqueSort;c.text=
a;c.isXMLDoc=D;c.contains=P})();var fb=/Until$/,gb=/^(?:parents|prevUntil|prevAll)/,hb=/,/;ka=Array.prototype.slice;var Ra=function(a,b,d){if(c.isFunction(b))return c.grep(a,function(e,i){return!!b.call(e,i,e)===d});else if(b.nodeType)return c.grep(a,function(e){return e===b===d});else if(typeof b==="string"){var f=c.grep(a,function(e){return e.nodeType===1});if(w.test(b))return c.filter(b,f,!d);else b=c.filter(b,f)}return c.grep(a,function(e){return c.inArray(e,b)>=0===d})};c.fn.extend({find:function(a){for(var b=
this.pushStack("","find",a),d=0,f=0,e=this.length;f<e;f++){d=b.length;c.find(a,this[f],b);if(f>0)for(var i=d;i<b.length;i++)for(var j=0;j<d;j++)if(b[j]===b[i]){b.splice(i--,1);break}}return b},has:function(a){var b=c(a);return this.filter(function(){for(var d=0,f=b.length;d<f;d++)if(c.contains(this,b[d]))return true})},not:function(a){return this.pushStack(Ra(this,a,false),"not",a)},filter:function(a){return this.pushStack(Ra(this,a,true),"filter",a)},is:function(a){return!!a&&c.filter(a,this).length>
0},closest:function(a,b){if(c.isArray(a)){var d=[],f=this[0],e,i={},j;if(f&&a.length){e=0;for(var q=a.length;e<q;e++){j=a[e];i[j]||(i[j]=c.expr.match.POS.test(j)?c(j,b||this.context):j)}for(;f&&f.ownerDocument&&f!==b;){for(j in i){e=i[j];if(e.jquery?e.index(f)>-1:c(f).is(e)){d.push({selector:j,elem:f});delete i[j]}}f=f.parentNode}}return d}var k=c.expr.match.POS.test(a)?c(a,b||this.context):null;return this.map(function(o,u){for(;u&&u.ownerDocument&&u!==b;){if(k?k.index(u)>-1:c(u).is(a))return u;
u=u.parentNode}return null})},index:function(a){if(!a||typeof a==="string")return c.inArray(this[0],a?c(a):this.parent().children());return c.inArray(a.jquery?a[0]:a,this)},add:function(a,b){a=typeof a==="string"?c(a,b||this.context):c.makeArray(a);b=c.merge(this.get(),a);return this.pushStack(ma(a[0])||ma(b[0])?b:c.unique(b))},andSelf:function(){return this.add(this.prevObject)}});c.each({parent:function(a){return(a=a.parentNode)&&a.nodeType!==11?a:null},parents:function(a){return c.dir(a,"parentNode")},
parentsUntil:function(a,b,d){return c.dir(a,"parentNode",d)},next:function(a){return c.nth(a,2,"nextSibling")},prev:function(a){return c.nth(a,2,"previousSibling")},nextAll:function(a){return c.dir(a,"nextSibling")},prevAll:function(a){return c.dir(a,"previousSibling")},nextUntil:function(a,b,d){return c.dir(a,"nextSibling",d)},prevUntil:function(a,b,d){return c.dir(a,"previousSibling",d)},siblings:function(a){return c.sibling(a.parentNode.firstChild,a)},children:function(a){return c.sibling(a.firstChild)},
contents:function(a){return c.nodeName(a,"iframe")?a.contentDocument||a.contentWindow.document:c.makeArray(a.childNodes)}},function(a,b){c.fn[a]=function(d,f){var e=c.map(this,b,d);fb.test(a)||(f=d);if(f&&typeof f==="string")e=c.filter(f,e);e=this.length>1?c.unique(e):e;if((this.length>1||hb.test(f))&&gb.test(a))e=e.reverse();return this.pushStack(e,a,ka.call(arguments).join(","))}});c.extend({filter:function(a,b,d){if(d)a=":not("+a+")";return c.find.matches(a,b)},dir:function(a,b,d){var f=[];for(a=
a[b];a&&a.nodeType!==9&&(d===A||a.nodeType!==1||!c(a).is(d));){a.nodeType===1&&f.push(a);a=a[b]}return f},nth:function(a,b,d){b=b||1;for(var f=0;a;a=a[d])if(a.nodeType===1&&++f===b)break;return a},sibling:function(a,b){for(var d=[];a;a=a.nextSibling)a.nodeType===1&&a!==b&&d.push(a);return d}});var Sa=/ jQuery\d+="(?:\d+|null)"/g,oa=/^\s+/,Ta=/(<([\w:]+)[^>]*?)\/>/g,ib=/^(?:area|br|col|embed|hr|img|input|link|meta|param)$/i,Ua=/<([\w:]+)/,jb=/<tbody/i,kb=/<|&#?\w+;/,Ea=/<script|<object|<embed|<option|<style/i,
Fa=/checked\s*(?:[^=]|=\s*.checked.)/i,Va=function(a,b,d){return ib.test(d)?a:b+"></"+d+">"},Q={option:[1,"<select multiple='multiple'>","</select>"],legend:[1,"<fieldset>","</fieldset>"],thead:[1,"<table>","</table>"],tr:[2,"<table><tbody>","</tbody></table>"],td:[3,"<table><tbody><tr>","</tr></tbody></table>"],col:[2,"<table><tbody></tbody><colgroup>","</colgroup></table>"],area:[1,"<map>","</map>"],_default:[0,"",""]};Q.optgroup=Q.option;Q.tbody=Q.tfoot=Q.colgroup=Q.caption=Q.thead;Q.th=Q.td;if(!c.support.htmlSerialize)Q._default=
[1,"div<div>","</div>"];c.fn.extend({text:function(a){if(c.isFunction(a))return this.each(function(b){var d=c(this);d.text(a.call(this,b,d.text()))});if(typeof a!=="object"&&a!==A)return this.empty().append((this[0]&&this[0].ownerDocument||m).createTextNode(a));return c.text(this)},wrapAll:function(a){if(c.isFunction(a))return this.each(function(d){c(this).wrapAll(a.call(this,d))});if(this[0]){var b=c(a,this[0].ownerDocument).eq(0).clone(true);this[0].parentNode&&b.insertBefore(this[0]);b.map(function(){for(var d=
this;d.firstChild&&d.firstChild.nodeType===1;)d=d.firstChild;return d}).append(this)}return this},wrapInner:function(a){if(c.isFunction(a))return this.each(function(b){c(this).wrapInner(a.call(this,b))});return this.each(function(){var b=c(this),d=b.contents();d.length?d.wrapAll(a):b.append(a)})},wrap:function(a){return this.each(function(){c(this).wrapAll(a)})},unwrap:function(){return this.parent().each(function(){c.nodeName(this,"body")||c(this).replaceWith(this.childNodes)}).end()},append:function(){return this.domManip(arguments,
true,function(a){this.nodeType===1&&this.appendChild(a)})},prepend:function(){return this.domManip(arguments,true,function(a){this.nodeType===1&&this.insertBefore(a,this.firstChild)})},before:function(){if(this[0]&&this[0].parentNode)return this.domManip(arguments,false,function(b){this.parentNode.insertBefore(b,this)});else if(arguments.length){var a=c(arguments[0]);a.push.apply(a,this.toArray());return this.pushStack(a,"before",arguments)}},after:function(){if(this[0]&&this[0].parentNode)return this.domManip(arguments,
false,function(b){this.parentNode.insertBefore(b,this.nextSibling)});else if(arguments.length){var a=this.pushStack(this,"after",arguments);a.push.apply(a,c(arguments[0]).toArray());return a}},remove:function(a,b){for(var d=0,f;(f=this[d])!=null;d++)if(!a||c.filter(a,[f]).length){if(!b&&f.nodeType===1){c.cleanData(f.getElementsByTagName("*"));c.cleanData([f])}f.parentNode&&f.parentNode.removeChild(f)}return this},empty:function(){for(var a=0,b;(b=this[a])!=null;a++)for(b.nodeType===1&&c.cleanData(b.getElementsByTagName("*"));b.firstChild;)b.removeChild(b.firstChild);
return this},clone:function(a){var b=this.map(function(){if(!c.support.noCloneEvent&&!c.isXMLDoc(this)){var d=this.outerHTML,f=this.ownerDocument;if(!d){d=f.createElement("div");d.appendChild(this.cloneNode(true));d=d.innerHTML}return c.clean([d.replace(Sa,"").replace(/=([^="'>\s]+\/)>/g,'="$1">').replace(oa,"")],f)[0]}else return this.cloneNode(true)});if(a===true){T(this,b);T(this.find("*"),b.find("*"))}return b},html:function(a){if(a===A)return this[0]&&this[0].nodeType===1?this[0].innerHTML.replace(Sa,
""):null;else if(typeof a==="string"&&!Ea.test(a)&&(c.support.leadingWhitespace||!oa.test(a))&&!Q[(Ua.exec(a)||["",""])[1].toLowerCase()]){a=a.replace(Ta,Va);try{for(var b=0,d=this.length;b<d;b++)if(this[b].nodeType===1){c.cleanData(this[b].getElementsByTagName("*"));this[b].innerHTML=a}}catch(f){this.empty().append(a)}}else c.isFunction(a)?this.each(function(e){var i=c(this),j=i.html();i.empty().append(function(){return a.call(this,e,j)})}):this.empty().append(a);return this},replaceWith:function(a){if(this[0]&&
this[0].parentNode){if(c.isFunction(a))return this.each(function(b){var d=c(this),f=d.html();d.replaceWith(a.call(this,b,f))});if(typeof a!=="string")a=c(a).detach();return this.each(function(){var b=this.nextSibling,d=this.parentNode;c(this).remove();b?c(b).before(a):c(d).append(a)})}else return this.pushStack(c(c.isFunction(a)?a():a),"replaceWith",a)},detach:function(a){return this.remove(a,true)},domManip:function(a,b,d){function f(z){return c.nodeName(z,"table")?z.getElementsByTagName("tbody")[0]||
z.appendChild(z.ownerDocument.createElement("tbody")):z}var e,i,j=a[0],q=[],k;if(!c.support.checkClone&&arguments.length===3&&typeof j==="string"&&Fa.test(j))return this.each(function(){c(this).domManip(a,b,d,true)});if(c.isFunction(j))return this.each(function(z){var G=c(this);a[0]=j.call(this,z,b?G.html():A);G.domManip(a,b,d)});if(this[0]){e=j&&j.parentNode;e=c.support.parentNode&&e&&e.nodeType===11&&e.childNodes.length===this.length?{fragment:e}:ia(a,this,q);k=e.fragment;if(i=k.childNodes.length===
1?(k=k.firstChild):k.firstChild){b=b&&c.nodeName(i,"tr");for(var o=0,u=this.length;o<u;o++)d.call(b?f(this[o],i):this[o],o>0||e.cacheable||this.length>1?k.cloneNode(true):k)}q.length&&c.each(q,N)}return this}});c.fragments={};c.each({appendTo:"append",prependTo:"prepend",insertBefore:"before",insertAfter:"after",replaceAll:"replaceWith"},function(a,b){c.fn[a]=function(d){var f=[];d=c(d);var e=this.length===1&&this[0].parentNode;if(e&&e.nodeType===11&&e.childNodes.length===1&&d.length===1){d[b](this[0]);
return this}else{e=0;for(var i=d.length;e<i;e++){var j=(e>0?this.clone(true):this).get();c.fn[b].apply(c(d[e]),j);f=f.concat(j)}return this.pushStack(f,a,d.selector)}}});c.extend({clean:function(a,b,d,f){b=b||m;if(typeof b.createElement==="undefined")b=b.ownerDocument||b[0]&&b[0].ownerDocument||m;for(var e=[],i=0,j;(j=a[i])!=null;i++){if(typeof j==="number")j+="";if(j){if(typeof j==="string"&&!kb.test(j))j=b.createTextNode(j);else if(typeof j==="string"){j=j.replace(Ta,Va);var q=(Ua.exec(j)||["",
""])[1].toLowerCase(),k=Q[q]||Q._default,o=k[0],u=b.createElement("div");for(u.innerHTML=k[1]+j+k[2];o--;)u=u.lastChild;if(!c.support.tbody){o=jb.test(j);q=q==="table"&&!o?u.firstChild&&u.firstChild.childNodes:k[1]==="<table>"&&!o?u.childNodes:[];for(k=q.length-1;k>=0;--k)c.nodeName(q[k],"tbody")&&!q[k].childNodes.length&&q[k].parentNode.removeChild(q[k])}!c.support.leadingWhitespace&&oa.test(j)&&u.insertBefore(b.createTextNode(oa.exec(j)[0]),u.firstChild);j=u.childNodes}if(j.nodeType)e.push(j);else e=
c.merge(e,j)}}if(d)for(i=0;e[i];i++)if(f&&c.nodeName(e[i],"script")&&(!e[i].type||e[i].type.toLowerCase()==="text/javascript"))f.push(e[i].parentNode?e[i].parentNode.removeChild(e[i]):e[i]);else{e[i].nodeType===1&&e.splice.apply(e,[i+1,0].concat(c.makeArray(e[i].getElementsByTagName("script"))));d.appendChild(e[i])}return e},cleanData:function(a){for(var b,d,f=c.cache,e=c.event.special,i=c.support.deleteExpando,j=0,q;(q=a[j])!=null;j++)if(d=q[c.expando]){b=f[d];if(b.events)for(var k in b.events)e[k]?
c.event.remove(q,k):La(q,k,b.handle);if(i)delete q[c.expando];else q.removeAttribute&&q.removeAttribute(c.expando);delete f[d]}}});var lb=/z-?index|font-?weight|opacity|zoom|line-?height/i,Wa=/alpha\([^)]*\)/,Xa=/opacity=([^)]*)/,za=/float/i,Aa=/-([a-z])/ig,mb=/([A-Z])/g,nb=/^-?\d+(?:px)?$/i,ob=/^-?\d/,pb={position:"absolute",visibility:"hidden",display:"block"},qb=["Left","Right"],rb=["Top","Bottom"],sb=m.defaultView&&m.defaultView.getComputedStyle,Ya=c.support.cssFloat?"cssFloat":"styleFloat",Ba=
function(a,b){return b.toUpperCase()};c.fn.css=function(a,b){return ga(this,a,b,true,function(d,f,e){if(e===A)return c.curCSS(d,f);if(typeof e==="number"&&!lb.test(f))e+="px";c.style(d,f,e)})};c.extend({style:function(a,b,d){if(!a||a.nodeType===3||a.nodeType===8)return A;if((b==="width"||b==="height")&&parseFloat(d)<0)d=A;var f=a.style||a,e=d!==A;if(!c.support.opacity&&b==="opacity"){if(e){f.zoom=1;b=parseInt(d,10)+""==="NaN"?"":"alpha(opacity="+d*100+")";a=f.filter||c.curCSS(a,"filter")||"";f.filter=
Wa.test(a)?a.replace(Wa,b):b}return f.filter&&f.filter.indexOf("opacity=")>=0?parseFloat(Xa.exec(f.filter)[1])/100+"":""}if(za.test(b))b=Ya;b=b.replace(Aa,Ba);if(e)f[b]=d;return f[b]},css:function(a,b,d,f){if(b==="width"||b==="height"){var e,i=b==="width"?qb:rb;d=function(){e=b==="width"?a.offsetWidth:a.offsetHeight;f!=="border"&&c.each(i,function(){f||(e-=parseFloat(c.curCSS(a,"padding"+this,true))||0);if(f==="margin")e+=parseFloat(c.curCSS(a,"margin"+this,true))||0;else e-=parseFloat(c.curCSS(a,
"border"+this+"Width",true))||0})};a.offsetWidth!==0?d():c.swap(a,pb,d);return Math.max(0,Math.round(e))}return c.curCSS(a,b,d)},curCSS:function(a,b,d){var f,e=a.style;if(!c.support.opacity&&b==="opacity"&&a.currentStyle){f=Xa.test(a.currentStyle.filter||"")?parseFloat(RegExp.$1)/100+"":"";return f===""?"1":f}if(za.test(b))b=Ya;if(!d&&e&&e[b])f=e[b];else if(sb){if(za.test(b))b="float";b=b.replace(mb,"-$1").toLowerCase();e=a.ownerDocument.defaultView;if(!e)return null;if(a=e.getComputedStyle(a,null))f=
a.getPropertyValue(b);if(b==="opacity"&&f==="")f="1"}else if(a.currentStyle){d=b.replace(Aa,Ba);f=a.currentStyle[b]||a.currentStyle[d];if(!nb.test(f)&&ob.test(f)){b=e.left;var i=a.runtimeStyle.left;a.runtimeStyle.left=a.currentStyle.left;e.left=d==="fontSize"?"1em":f||0;f=e.pixelLeft+"px";e.left=b;a.runtimeStyle.left=i}}return f},swap:function(a,b,d){var f={};for(var e in b){f[e]=a.style[e];a.style[e]=b[e]}d.call(a);for(e in b)a.style[e]=f[e]}});if(c.expr&&c.expr.filters){c.expr.filters.hidden=function(a){var b=
a.offsetWidth,d=a.offsetHeight,f=a.nodeName.toLowerCase()==="tr";return b===0&&d===0&&!f?true:b>0&&d>0&&!f?false:c.curCSS(a,"display")==="none"};c.expr.filters.visible=function(a){return!c.expr.filters.hidden(a)}}var tb=R(),ub=/<script(.|\s)*?\/script>/gi,vb=/select|textarea/i,wb=/color|date|datetime|email|hidden|month|number|password|range|search|tel|text|time|url|week/i,fa=/=\?(&|$)/,Ca=/\?/,xb=/(\?|&)_=.*?(&|$)/,yb=/^(\w+:)?\/\/([^\/?#]+)/,zb=/%20/g,Ab=c.fn.load;c.fn.extend({load:function(a,b,
d){if(typeof a!=="string")return Ab.call(this,a);else if(!this.length)return this;var f=a.indexOf(" ");if(f>=0){var e=a.slice(f,a.length);a=a.slice(0,f)}f="GET";if(b)if(c.isFunction(b)){d=b;b=null}else if(typeof b==="object"){b=c.param(b,c.ajaxSettings.traditional);f="POST"}var i=this;c.ajax({url:a,type:f,dataType:"html",data:b,complete:function(j,q){if(q==="success"||q==="notmodified")i.html(e?c("<div />").append(j.responseText.replace(ub,"")).find(e):j.responseText);d&&i.each(d,[j.responseText,
q,j])}});return this},serialize:function(){return c.param(this.serializeArray())},serializeArray:function(){return this.map(function(){return this.elements?c.makeArray(this.elements):this}).filter(function(){return this.name&&!this.disabled&&(this.checked||vb.test(this.nodeName)||wb.test(this.type))}).map(function(a,b){a=c(this).val();return a==null?null:c.isArray(a)?c.map(a,function(d){return{name:b.name,value:d}}):{name:b.name,value:a}}).get()}});c.each("ajaxStart ajaxStop ajaxComplete ajaxError ajaxSuccess ajaxSend".split(" "),
function(a,b){c.fn[b]=function(d){return this.bind(b,d)}});c.extend({get:function(a,b,d,f){if(c.isFunction(b)){f=f||d;d=b;b=null}return c.ajax({type:"GET",url:a,data:b,success:d,dataType:f})},getScript:function(a,b){return c.get(a,null,b,"script")},getJSON:function(a,b,d){return c.get(a,b,d,"json")},post:function(a,b,d,f){if(c.isFunction(b)){f=f||d;d=b;b={}}return c.ajax({type:"POST",url:a,data:b,success:d,dataType:f})},ajaxSetup:function(a){c.extend(c.ajaxSettings,a)},ajaxSettings:{url:location.href,
global:true,type:"GET",contentType:"application/x-www-form-urlencoded",processData:true,async:true,xhr:E.XMLHttpRequest&&(E.location.protocol!=="file:"||!E.ActiveXObject)?function(){return new E.XMLHttpRequest}:function(){try{return new E.ActiveXObject("Microsoft.XMLHTTP")}catch(a){}},accepts:{xml:"application/xml, text/xml",html:"text/html",script:"text/javascript, application/javascript",json:"application/json, text/javascript",text:"text/plain",_default:"*/*"}},lastModified:{},etag:{},ajax:function(a){function b(){e.success&&
e.success.call(k,q,j,D);e.global&&f("ajaxSuccess",[D,e])}function d(){e.complete&&e.complete.call(k,D,j);e.global&&f("ajaxComplete",[D,e]);e.global&&!--c.active&&c.event.trigger("ajaxStop")}function f(t,s){(e.context?c(e.context):c.event).trigger(t,s)}var e=c.extend(true,{},c.ajaxSettings,a),i,j,q,k=a&&a.context||e,o=e.type.toUpperCase();if(e.data&&e.processData&&typeof e.data!=="string")e.data=c.param(e.data,e.traditional);if(e.dataType==="jsonp"){if(o==="GET")fa.test(e.url)||(e.url+=(Ca.test(e.url)?
"&":"?")+(e.jsonp||"callback")+"=?");else if(!e.data||!fa.test(e.data))e.data=(e.data?e.data+"&":"")+(e.jsonp||"callback")+"=?";e.dataType="json"}if(e.dataType==="json"&&(e.data&&fa.test(e.data)||fa.test(e.url))){i=e.jsonpCallback||"jsonp"+tb++;if(e.data)e.data=(e.data+"").replace(fa,"="+i+"$1");e.url=e.url.replace(fa,"="+i+"$1");e.dataType="script";E[i]=E[i]||function(t){q=t;b();d();E[i]=A;try{delete E[i]}catch(s){}G&&G.removeChild(I)}}if(e.dataType==="script"&&e.cache===null)e.cache=false;if(e.cache===
false&&o==="GET"){var u=R(),z=e.url.replace(xb,"$1_="+u+"$2");e.url=z+(z===e.url?(Ca.test(e.url)?"&":"?")+"_="+u:"")}if(e.data&&o==="GET")e.url+=(Ca.test(e.url)?"&":"?")+e.data;e.global&&!c.active++&&c.event.trigger("ajaxStart");u=(u=yb.exec(e.url))&&(u[1]&&u[1]!==location.protocol||u[2]!==location.host);if(e.dataType==="script"&&o==="GET"&&u){var G=m.getElementsByTagName("head")[0]||m.documentElement,I=m.createElement("script");I.src=e.url;if(e.scriptCharset)I.charset=e.scriptCharset;if(!i){var H=
false;I.onload=I.onreadystatechange=function(){if(!H&&(!this.readyState||this.readyState==="loaded"||this.readyState==="complete")){H=true;b();d();I.onload=I.onreadystatechange=null;G&&I.parentNode&&G.removeChild(I)}}}G.insertBefore(I,G.firstChild);return A}var P=false,D=e.xhr();if(D){e.username?D.open(o,e.url,e.async,e.username,e.password):D.open(o,e.url,e.async);try{if(e.data||a&&a.contentType)D.setRequestHeader("Content-Type",e.contentType);if(e.ifModified){c.lastModified[e.url]&&D.setRequestHeader("If-Modified-Since",
c.lastModified[e.url]);c.etag[e.url]&&D.setRequestHeader("If-None-Match",c.etag[e.url])}u||D.setRequestHeader("X-Requested-With","XMLHttpRequest");D.setRequestHeader("Accept",e.dataType&&e.accepts[e.dataType]?e.accepts[e.dataType]+", */*":e.accepts._default)}catch(ya){}if(e.beforeSend&&e.beforeSend.call(k,D,e)===false){e.global&&!--c.active&&c.event.trigger("ajaxStop");D.abort();return false}e.global&&f("ajaxSend",[D,e]);var g=D.onreadystatechange=function(t){if(!D||D.readyState===0||t==="abort"){P||
d();P=true;if(D)D.onreadystatechange=c.noop}else if(!P&&D&&(D.readyState===4||t==="timeout")){P=true;D.onreadystatechange=c.noop;j=t==="timeout"?"timeout":!c.httpSuccess(D)?"error":e.ifModified&&c.httpNotModified(D,e.url)?"notmodified":"success";var s;if(j==="success")try{q=c.httpData(D,e.dataType,e)}catch(B){j="parsererror";s=B}if(j==="success"||j==="notmodified")i||b();else c.handleError(e,D,j,s);d();t==="timeout"&&D.abort();if(e.async)D=null}};try{var h=D.abort;D.abort=function(){D&&h.call(D);
g("abort")}}catch(l){}e.async&&e.timeout>0&&setTimeout(function(){D&&!P&&g("timeout")},e.timeout);try{D.send(o==="POST"||o==="PUT"||o==="DELETE"?e.data:null)}catch(n){c.handleError(e,D,null,n);d()}e.async||g();return D}},handleError:function(a,b,d,f){if(a.error)a.error.call(a.context||a,b,d,f);if(a.global)(a.context?c(a.context):c.event).trigger("ajaxError",[b,a,f])},active:0,httpSuccess:function(a){try{return!a.status&&location.protocol==="file:"||a.status>=200&&a.status<300||a.status===304||a.status===
1223||a.status===0}catch(b){}return false},httpNotModified:function(a,b){var d=a.getResponseHeader("Last-Modified"),f=a.getResponseHeader("Etag");if(d)c.lastModified[b]=d;if(f)c.etag[b]=f;return a.status===304||a.status===0},httpData:function(a,b,d){var f=a.getResponseHeader("content-type")||"",e=b==="xml"||!b&&f.indexOf("xml")>=0;a=e?a.responseXML:a.responseText;e&&a.documentElement.nodeName==="parsererror"&&c.error("parsererror");if(d&&d.dataFilter)a=d.dataFilter(a,b);if(typeof a==="string")if(b===
"json"||!b&&f.indexOf("json")>=0)a=c.parseJSON(a);else if(b==="script"||!b&&f.indexOf("javascript")>=0)c.globalEval(a);return a},param:function(a,b){function d(j,q){if(c.isArray(q))c.each(q,function(k,o){b||/\[\]$/.test(j)?f(j,o):d(j+"["+(typeof o==="object"||c.isArray(o)?k:"")+"]",o)});else!b&&q!=null&&typeof q==="object"?c.each(q,function(k,o){d(j+"["+k+"]",o)}):f(j,q)}function f(j,q){q=c.isFunction(q)?q():q;e[e.length]=encodeURIComponent(j)+"="+encodeURIComponent(q)}var e=[];if(b===A)b=c.ajaxSettings.traditional;
if(c.isArray(a)||a.jquery)c.each(a,function(){f(this.name,this.value)});else for(var i in a)d(i,a[i]);return e.join("&").replace(zb,"+")}});var Da={},Bb=/toggle|show|hide/,Cb=/^([+-]=)?([\d+-.]+)(.*)$/,pa,Ga=[["height","marginTop","marginBottom","paddingTop","paddingBottom"],["width","marginLeft","marginRight","paddingLeft","paddingRight"],["opacity"]];c.fn.extend({show:function(a,b){if(a||a===0)return this.animate(U("show",3),a,b);else{a=0;for(b=this.length;a<b;a++){var d=c.data(this[a],"olddisplay");
this[a].style.display=d||"";if(c.css(this[a],"display")==="none"){d=this[a].nodeName;var f;if(Da[d])f=Da[d];else{var e=c("<"+d+" />").appendTo("body");f=e.css("display");if(f==="none")f="block";e.remove();Da[d]=f}c.data(this[a],"olddisplay",f)}}a=0;for(b=this.length;a<b;a++)this[a].style.display=c.data(this[a],"olddisplay")||"";return this}},hide:function(a,b){if(a||a===0)return this.animate(U("hide",3),a,b);else{a=0;for(b=this.length;a<b;a++){var d=c.data(this[a],"olddisplay");!d&&d!=="none"&&c.data(this[a],
"olddisplay",c.css(this[a],"display"))}a=0;for(b=this.length;a<b;a++)this[a].style.display="none";return this}},_toggle:c.fn.toggle,toggle:function(a,b){var d=typeof a==="boolean";if(c.isFunction(a)&&c.isFunction(b))this._toggle.apply(this,arguments);else a==null||d?this.each(function(){var f=d?a:c(this).is(":hidden");c(this)[f?"show":"hide"]()}):this.animate(U("toggle",3),a,b);return this},fadeTo:function(a,b,d){return this.filter(":hidden").css("opacity",0).show().end().animate({opacity:b},a,d)},
animate:function(a,b,d,f){var e=c.speed(b,d,f);if(c.isEmptyObject(a))return this.each(e.complete);return this[e.queue===false?"each":"queue"](function(){var i=c.extend({},e),j,q=this.nodeType===1&&c(this).is(":hidden"),k=this;for(j in a){var o=j.replace(Aa,Ba);if(j!==o){a[o]=a[j];delete a[j];j=o}if(a[j]==="hide"&&q||a[j]==="show"&&!q)return i.complete.call(this);if((j==="height"||j==="width")&&this.style){i.display=c.css(this,"display");i.overflow=this.style.overflow}if(c.isArray(a[j])){(i.specialEasing=
i.specialEasing||{})[j]=a[j][1];a[j]=a[j][0]}}if(i.overflow!=null)this.style.overflow="hidden";i.curAnim=c.extend({},a);c.each(a,function(u,z){var G=new c.fx(k,i,u);if(Bb.test(z))G[z==="toggle"?q?"show":"hide":z](a);else{var I=Cb.exec(z),H=G.cur(true)||0;if(I){z=parseFloat(I[2]);var P=I[3]||"px";if(P!=="px"){k.style[u]=(z||1)+P;H=(z||1)/G.cur(true)*H;k.style[u]=H+P}if(I[1])z=(I[1]==="-="?-1:1)*z+H;G.custom(H,z,P)}else G.custom(H,z,"")}});return true})},stop:function(a,b){var d=c.timers;a&&this.queue([]);
this.each(function(){for(var f=d.length-1;f>=0;f--)if(d[f].elem===this){b&&d[f](true);d.splice(f,1)}});b||this.dequeue();return this}});c.each({slideDown:U("show",1),slideUp:U("hide",1),slideToggle:U("toggle",1),fadeIn:{opacity:"show"},fadeOut:{opacity:"hide"}},function(a,b){c.fn[a]=function(d,f){return this.animate(b,d,f)}});c.extend({speed:function(a,b,d){var f=a&&typeof a==="object"?a:{complete:d||!d&&b||c.isFunction(a)&&a,duration:a,easing:d&&b||b&&!c.isFunction(b)&&b};f.duration=c.fx.off?0:typeof f.duration===
"number"?f.duration:c.fx.speeds[f.duration]||c.fx.speeds._default;f.old=f.complete;f.complete=function(){f.queue!==false&&c(this).dequeue();c.isFunction(f.old)&&f.old.call(this)};return f},easing:{linear:function(a,b,d,f){return d+f*a},swing:function(a,b,d,f){return(-Math.cos(a*Math.PI)/2+0.5)*f+d}},timers:[],fx:function(a,b,d){this.options=b;this.elem=a;this.prop=d;if(!b.orig)b.orig={}}});c.fx.prototype={update:function(){this.options.step&&this.options.step.call(this.elem,this.now,this);(c.fx.step[this.prop]||
c.fx.step._default)(this);if((this.prop==="height"||this.prop==="width")&&this.elem.style)this.elem.style.display="block"},cur:function(a){if(this.elem[this.prop]!=null&&(!this.elem.style||this.elem.style[this.prop]==null))return this.elem[this.prop];return(a=parseFloat(c.css(this.elem,this.prop,a)))&&a>-10000?a:parseFloat(c.curCSS(this.elem,this.prop))||0},custom:function(a,b,d){function f(i){return e.step(i)}this.startTime=R();this.start=a;this.end=b;this.unit=d||this.unit||"px";this.now=this.start;
this.pos=this.state=0;var e=this;f.elem=this.elem;if(f()&&c.timers.push(f)&&!pa)pa=setInterval(c.fx.tick,13)},show:function(){this.options.orig[this.prop]=c.style(this.elem,this.prop);this.options.show=true;this.custom(this.prop==="width"||this.prop==="height"?1:0,this.cur());c(this.elem).show()},hide:function(){this.options.orig[this.prop]=c.style(this.elem,this.prop);this.options.hide=true;this.custom(this.cur(),0)},step:function(a){var b=R(),d=true;if(a||b>=this.options.duration+this.startTime){this.now=
this.end;this.pos=this.state=1;this.update();this.options.curAnim[this.prop]=true;for(var f in this.options.curAnim)if(this.options.curAnim[f]!==true)d=false;if(d){if(this.options.display!=null){this.elem.style.overflow=this.options.overflow;a=c.data(this.elem,"olddisplay");this.elem.style.display=a?a:this.options.display;if(c.css(this.elem,"display")==="none")this.elem.style.display="block"}this.options.hide&&c(this.elem).hide();if(this.options.hide||this.options.show)for(var e in this.options.curAnim)c.style(this.elem,
e,this.options.orig[e]);this.options.complete.call(this.elem)}return false}else{e=b-this.startTime;this.state=e/this.options.duration;a=this.options.easing||(c.easing.swing?"swing":"linear");this.pos=c.easing[this.options.specialEasing&&this.options.specialEasing[this.prop]||a](this.state,e,0,1,this.options.duration);this.now=this.start+(this.end-this.start)*this.pos;this.update()}return true}};c.extend(c.fx,{tick:function(){for(var a=c.timers,b=0;b<a.length;b++)a[b]()||a.splice(b--,1);a.length||
c.fx.stop()},stop:function(){clearInterval(pa);pa=null},speeds:{slow:600,fast:200,_default:400},step:{opacity:function(a){c.style(a.elem,"opacity",a.now)},_default:function(a){if(a.elem.style&&a.elem.style[a.prop]!=null)a.elem.style[a.prop]=(a.prop==="width"||a.prop==="height"?Math.max(0,a.now):a.now)+a.unit;else a.elem[a.prop]=a.now}}});if(c.expr&&c.expr.filters)c.expr.filters.animated=function(a){return c.grep(c.timers,function(b){return a===b.elem}).length};c.fn.offset="getBoundingClientRect"in
m.documentElement?function(a){var b=this[0];if(a)return this.each(function(e){c.offset.setOffset(this,a,e)});if(!b||!b.ownerDocument)return null;if(b===b.ownerDocument.body)return c.offset.bodyOffset(b);var d=b.getBoundingClientRect(),f=b.ownerDocument;b=f.body;f=f.documentElement;return{top:d.top+(self.pageYOffset||c.support.boxModel&&f.scrollTop||b.scrollTop)-(f.clientTop||b.clientTop||0),left:d.left+(self.pageXOffset||c.support.boxModel&&f.scrollLeft||b.scrollLeft)-(f.clientLeft||b.clientLeft||
0)}}:function(a){var b=this[0];if(a)return this.each(function(u){c.offset.setOffset(this,a,u)});if(!b||!b.ownerDocument)return null;if(b===b.ownerDocument.body)return c.offset.bodyOffset(b);c.offset.initialize();var d=b.offsetParent,f=b,e=b.ownerDocument,i,j=e.documentElement,q=e.body;f=(e=e.defaultView)?e.getComputedStyle(b,null):b.currentStyle;for(var k=b.offsetTop,o=b.offsetLeft;(b=b.parentNode)&&b!==q&&b!==j;){if(c.offset.supportsFixedPosition&&f.position==="fixed")break;i=e?e.getComputedStyle(b,
null):b.currentStyle;k-=b.scrollTop;o-=b.scrollLeft;if(b===d){k+=b.offsetTop;o+=b.offsetLeft;if(c.offset.doesNotAddBorder&&!(c.offset.doesAddBorderForTableAndCells&&/^t(able|d|h)$/i.test(b.nodeName))){k+=parseFloat(i.borderTopWidth)||0;o+=parseFloat(i.borderLeftWidth)||0}f=d;d=b.offsetParent}if(c.offset.subtractsBorderForOverflowNotVisible&&i.overflow!=="visible"){k+=parseFloat(i.borderTopWidth)||0;o+=parseFloat(i.borderLeftWidth)||0}f=i}if(f.position==="relative"||f.position==="static"){k+=q.offsetTop;
o+=q.offsetLeft}if(c.offset.supportsFixedPosition&&f.position==="fixed"){k+=Math.max(j.scrollTop,q.scrollTop);o+=Math.max(j.scrollLeft,q.scrollLeft)}return{top:k,left:o}};c.offset={initialize:function(){var a=m.body,b=m.createElement("div"),d,f,e,i=parseFloat(c.curCSS(a,"marginTop",true))||0;c.extend(b.style,{position:"absolute",top:0,left:0,margin:0,border:0,width:"1px",height:"1px",visibility:"hidden"});b.innerHTML="<div style='position:absolute;top:0;left:0;margin:0;border:5px solid #000;padding:0;width:1px;height:1px;'><div></div></div><table style='position:absolute;top:0;left:0;margin:0;border:5px solid #000;padding:0;width:1px;height:1px;' cellpadding='0' cellspacing='0'><tr><td></td></tr></table>";
a.insertBefore(b,a.firstChild);d=b.firstChild;f=d.firstChild;e=d.nextSibling.firstChild.firstChild;this.doesNotAddBorder=f.offsetTop!==5;this.doesAddBorderForTableAndCells=e.offsetTop===5;f.style.position="fixed";f.style.top="20px";this.supportsFixedPosition=f.offsetTop===20||f.offsetTop===15;f.style.position=f.style.top="";d.style.overflow="hidden";d.style.position="relative";this.subtractsBorderForOverflowNotVisible=f.offsetTop===-5;this.doesNotIncludeMarginInBodyOffset=a.offsetTop!==i;a.removeChild(b);
c.offset.initialize=c.noop},bodyOffset:function(a){var b=a.offsetTop,d=a.offsetLeft;c.offset.initialize();if(c.offset.doesNotIncludeMarginInBodyOffset){b+=parseFloat(c.curCSS(a,"marginTop",true))||0;d+=parseFloat(c.curCSS(a,"marginLeft",true))||0}return{top:b,left:d}},setOffset:function(a,b,d){if(/static/.test(c.curCSS(a,"position")))a.style.position="relative";var f=c(a),e=f.offset(),i=parseInt(c.curCSS(a,"top",true),10)||0,j=parseInt(c.curCSS(a,"left",true),10)||0;if(c.isFunction(b))b=b.call(a,
d,e);d={top:b.top-e.top+i,left:b.left-e.left+j};"using"in b?b.using.call(a,d):f.css(d)}};c.fn.extend({position:function(){if(!this[0])return null;var a=this[0],b=this.offsetParent(),d=this.offset(),f=/^body|html$/i.test(b[0].nodeName)?{top:0,left:0}:b.offset();d.top-=parseFloat(c.curCSS(a,"marginTop",true))||0;d.left-=parseFloat(c.curCSS(a,"marginLeft",true))||0;f.top+=parseFloat(c.curCSS(b[0],"borderTopWidth",true))||0;f.left+=parseFloat(c.curCSS(b[0],"borderLeftWidth",true))||0;return{top:d.top-
f.top,left:d.left-f.left}},offsetParent:function(){return this.map(function(){for(var a=this.offsetParent||m.body;a&&!/^body|html$/i.test(a.nodeName)&&c.css(a,"position")==="static";)a=a.offsetParent;return a})}});c.each(["Left","Top"],function(a,b){var d="scroll"+b;c.fn[d]=function(f){var e=this[0],i;if(!e)return null;if(f!==A)return this.each(function(){if(i=aa(this))i.scrollTo(!a?f:c(i).scrollLeft(),a?f:c(i).scrollTop());else this[d]=f});else return(i=aa(e))?"pageXOffset"in i?i[a?"pageYOffset":
"pageXOffset"]:c.support.boxModel&&i.document.documentElement[d]||i.document.body[d]:e[d]}});c.each(["Height","Width"],function(a,b){var d=b.toLowerCase();c.fn["inner"+b]=function(){return this[0]?c.css(this[0],d,false,"padding"):null};c.fn["outer"+b]=function(f){return this[0]?c.css(this[0],d,false,f?"margin":"border"):null};c.fn[d]=function(f){var e=this[0];if(!e)return f==null?null:this;if(c.isFunction(f))return this.each(function(i){var j=c(this);j[d](f.call(this,i,j[d]()))});return"scrollTo"in
e&&e.document?e.document.compatMode==="CSS1Compat"&&e.document.documentElement["client"+b]||e.document.body["client"+b]:e.nodeType===9?Math.max(e.documentElement["client"+b],e.body["scroll"+b],e.documentElement["scroll"+b],e.body["offset"+b],e.documentElement["offset"+b]):f===A?c.css(e,d):this.css(d,typeof f==="string"?f:f+"px")}});E.jQuery=E.$=c;if(qa){require.callReady=c.callReady;require.def("jquery",function(){return c});require.def("jQuery",function(){return c})}})(window);
